### ISSUE TITLE
C++ Driver

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#100]
We want to build a very basic C++ client driver similar to the Go client we have right now. It would communicate with the server over gRPC and can run queries and mutations.

**Comment by joeblew99** [comment]
Have you looked at the cockroachdb code on github. they are also using grpc as their primary interop. I dont know if they have started building other client proxy libs yet.

Hope that helps a bit ?

**Comment by akhillb** [comment]
Is anyone working on this? Would like to help if no one else is working.

**Comment by manishrjain** [comment]
Sure, @akhillb You can pick this up. Don't think anyone else is working on this.

**Comment by akhillb** [comment]
Cool I am on it then.

**Comment by dcnewman** [comment]
@pawanrawal 
> We want to build a very basic C++ client driver similar to the Go client we have right now. 

If by that, you mean similar to dgraphclient-go, then I have a very rough cut here,

[github.com/dcnewman/dgraph](https://github.com/dcnewman/dgraph/commit/29b7c29695c85a374aa541e31d7d07511b7cd352
)

That very basic C++ client doesn't actually walk the returned Node in it's ouput.  Right now it just blindly outputs the uid and attribute from the root node which comes back.  That's easy to rectify; maybe in another evening.  But, not being a Go expert, I'm not too sure of the correct way to drop some C++ sources into a tree otherwise full of Go sources.  (I do know that I'm not doing it the correct way.)  But, I was pointed at this cool project the other evening, saw this in the wish list, and figured I'd spend a couple of hours familiarizing myself and trying to actually do something which might be useful.  Best way to learn something new is to jump right in.

**Comment by manishrjain** [comment]
C++ driver isn't high on demand. Closing this issue.
