### ISSUE TITLE
[Browser] Add available Queries/Schema as it is in conventional GraphiQL implementations

### ISSUE THREAD

**Issue by loganpowell** [dgraph-io/dgraph#1045]
I find it really nice to be able to see what I can query at each level of the schema in conventional GraphiQL interfaces. I might be asking for something that doesn't make complete sense in a Graph DB though, given that it can take any triple, but it would be nice if the Dgraph Browser mimicked the functions in GraphiQL (context-sensitive type ahead suggestions, side menu docs) somehow... Maybe help me understand why these features aren't currently in there?

**Comment by manishrjain** [comment]
Dgraph uses a modified version of GraphQL, which isn't backward compatible with GraphQL. We call it GraphQL+-. As such, it doesn't support GraphiQL interfaces.

**Comment by loganpowell** [comment]
Bear with me as I try to elaborate on this request with Dgraph (a true graph rather than a graph representation with predefined schema): in the case of a graphdb like Dgraph, perhaps the approach to get the same/similar functionality as is available in GraphiQL (in the context of this issue at least) would be to have the type ahead suggestions scoped to the current node/edge in the query... 

I.e., if I am using the Dgraph Browser:

{
  tourist(func: 
  <typeahead suggestions would be:
      near
      within
      contains
...

or

{
  tourist(func: near(
  <typeahead suggestions would be:
      loc
      polygon
...

One of the biggest benefits to developers using GraphiQL is that they can figure out the API by kinda just playing with it... discovering what's available each step of the way (down). The example could just as well be a matter of available edges/nodes directly linked to the current context rather than - in the case above - having to do with Dgraph's native features... that would make on boarding for developers within an organization (and their graph) as easy as it would make on boarding developers to Dgraph itself...

I hope this is making sense. Please forgive me if not.

Very excited to see what lies ahead and super stoked you guys are taking geospatial into consideration!

**Comment by MichaelJCompton** [comment]
The current dgraph browser does this a bit, but probably not as far ahead as you are thinking.  If I get as far as
```
{
  q(func: allofterms(name, "some director's name")) {
    d
```
I get options like

director.film
distribution_medium.films_distributed_in_this_medium
distributor.films_distributed
distributors

But at that point we don't have any type information to let us know which ones make sense.  E.G. if I haven't typed the "d" we don't know what options would make sense because how can we know it's a director name as opposed to a movie name or a genre name.  

I agree that being able to explore the schema really helps.  I find myself using queries like the following in the browser.

```
{
  q(func: allofterms(name, "Jane Campion")) {
    _predicate_
  }
}
```

Maybe in the first instance we need to do a better job of show people how they can explore their schema and data so they can work out what sorts of queries make sense?

**Comment by loganpowell** [comment]
I see. That makes sense. Perhaps you can give me your take on why you chose to go with a GraphQL-like syntax over something like SPARQL, Cypher or Gremlin?

**Comment by MichaelJCompton** [comment]
I haven't been around in Dgraph long enough to know the history of what drove the decisions (I can talk about comparisons).  

@manishrjain might comment, but he's away at the moment.

**Comment by loganpowell** [comment]
I would be interested in hearing more about 'why' graphql+- . Imo, what you guys are offering stands firm on its value proposition of a high-performing distributable graph db. I'm a little confused why you would make users learn a new graph query language when there are so many to choose from - in so doing you would be able to leverage the existing knowledge people have spent time cultivating in addition to participating in a larger ecosystem and community of graph db enthusiast users...

**Comment by manishrjain** [comment]
SPARQL and Cypher are based on SQL, which I think is ill-suited for querying a graph database. We got attracted towards GraphQL because the language query and the result are in the same format. You get back a graph from Dgraph, as opposed to a list of things from Cypher etc. It's a lot easier to go from a graph to a list, but not the other way round.

I think we need to look deeper into seeing how we can make look ahead work better, and if we can make GraphQL+- be backward compatible with GraphQL.

**Comment by georgecapsule8** [comment]
I agree with your points, but a cypherql interface would still be
awesome...esp for those of us who have invested a lot of energy and code in
the neo4j way :)

**Comment by manishrjain** [comment]
Once we reach v1.0, we'll consider Cypher, if it seems like many of Neo4j users want to switch over to Dgraph. For now, the main focus is to ensure that developers starting with Dgraph are getting a great experience from our query language.

**Comment by charbull** [comment]
Hello, why not rely on a W3C standard SPARQL?

Thx

**Comment by MichelDiz** [comment]
I think it would be possible something similar actually. Dgraph Browser could make an early loop with something like:

schema {
   type
   index
   reverse
   tokenizer
}

It would treat the result and offer as a suggestion at the time that the user is writing a new query.

And inside the queries can be loops with _predicate_ to find out what to add to the query body.

Now, functions and etc complicates. It would be interesting a kind of deep introspection and mapping with loops.

**Comment by manishrjain** [comment]
We'd try to reconcile GraphQL+- with GraphQL past v1.0.

**Comment by manishrjain** [comment]
Ratel does a bunch of this stuff now, i.e. showing schema, allowing users to explore data, and so on. Also, we have GraphQL support on Roadmap.
