### ISSUE TITLE
Separate Apache 2 client libraries into a folder or repo 

### ISSUE THREAD

**Issue by r-tock** [dgraph-io/dgraph#1085]
So that there is a clean separation between the two licenses and there aren't any shared code.

**Comment by manishrjain** [comment]
They're already in a different, `client` folder. Also, all those files use the Apache 2.0 license.

**Comment by manishrjain** [comment]
Good catch. We should change the licensing of x directory in that case.

**Comment by pawanrawal** [comment]
We have changed the license of all files in `protos`, `x` and `types` to Apache 2.0. These are the only packages imported by the client.

**Comment by r-tock** [comment]
Not done. types/facets are still in AGPL 
scalar_types_test.go.disable is in AGPL

I am sorry to say, but this is a bit sloppy. Doesn't give much confidence on how you will ensure preventing infecting AGPL to community codebases. Please be very careful with the execution of licensing as it will make a lot of your users very angry if you try to sneak in an AGPL in an Apache 2 library.

**Comment by pawanrawal** [comment]
Hey @r-tock 

Sorry, some files were still left over. I wrote a script to do this and missed some edge cases in that (recursive folders and files with extension other than `.go`). Should have done a grep for AGPL to verify.

**Comment by r-tock** [comment]
There is still work left 
https://github.com/dgraph-io/dgraph/blob/master/client/examples_test.go#L16
refers to rdf which is AGPL.

Wouldn't it be easier to move the client and "shared" files to its own folder to avoid pulling in AGPL in Apache 2. I am less confident that you can continue to maintain this without future you/others making mistakes.

**Comment by r-tock** [comment]
If you want inspiration https://github.com/neo4j/neo4j maintains separate folders for APGL and Apache licensed code.

**Comment by pawanrawal** [comment]
https://github.com/dgraph-io/dgraph/blob/master/client/examples_test.go#L16 is just used to render godocs. Client doesn't use the `rdf` package. Though, I have moved out the example to docs.dgraph.io so that there is no confusion.

We have a clean separation for now where we know which packages are imported by the client and we should be able to make sure that they have the appropriate license. The import paths are clean given the way how the current code is structured so we will keep it like this for now. Thanks for helping with this.
