### ISSUE TITLE
[Browser] Ctrl+C Autocomplete List

### ISSUE THREAD

**Issue by marwan-at-work** [dgraph-io/dgraph#1095]
The browser currently autocompletes when you type a letter. It would be great if we get a list of autocomplete props (by pressing Ctrl+C) without having to guess at letters. 

More so, the UI should be cursor-aware so that you can't show an edge that doesn't belong.

**Comment by manishrjain** [comment]
I think you probably don't even need to press ctrl+c. We could just show some suggestions by default, and refine them as you start typing.

> More so, the UI should be cursor-aware so that you can't show an edge that doesn't belong.

This is a lot harder to do, because it requires UI to parse and partially execute the query as a user types. Not something we want to build right now, possibly after v1.0.

**Comment by pawanrawal** [comment]
We show auto-complete suggestions by default and they are refined as you start typing.

**Comment by pawanrawal** [comment]
Auto-complete without typing doesn't make for a good UX, because it displays the list every time when the editor is in focus (even on pasting a query among other cases). 

I have changed it so that `Ctrl + Space` or `Cmd + Space` shows the list.
