### ISSUE TITLE
Modify context to contain more information about query latency.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1402]
It would be good if we can know how many PL's were fetched from disk vs cache for a query. 

We could maintain a wrapper struct around the `context.Context` that we pass to all functions in the query path. This wrapper struct could also maintain other information (e.g. disk seeks, time-taken for processing different levels of the subgraph etc.) which can optionally be returned to the user. This would help us in determining why a particular query is taking time.

**Comment by srh** [comment]
In general this would be a nice thing to make the query access other stuff through this parameter instead of using global variables in a bunch of different places.  There is no way to get a grasp on what the surface between query evaluation code and data storage/clustering code is right now without having some global picture of the entire codebase.

**Comment by manishrjain** [comment]
We'll use Open Census for request tracing. Tracked by #2257 .
