### ISSUE TITLE
dgraph consumes too much disk

### ISSUE THREAD

**Issue by flyfatasy** [dgraph-io/dgraph#1434]
We are using dgraph and now we finally import a graph with 1 billion nodes and 5 billion edges.  We consumed 800G disk. We are running dgraph0.8.1 on a ubuntu machine with 256 G memory and 2T ssd. We update the graph daily using dgraphloader. Everyday 2G(gzip file) rdfs is imported(10% are new data, 90% will be overwritten). Now dgraph consumes about 1.3T disk and the disk it consumed is still growing.

I know bager is used since dgraph 0.8.0. Now I am wondering whether more and more disk will be consumed by  bager(if so we have to add more disks). 

Below is the list of p directory of dgraph.

root@data-graph01:/data/dgraph/contactlist_graph/p# ls -lt | head 
total 1364250856
-rw-rw-r-- 1 dgraph dgraph  768988471 Sep 11 10:08 001218.vlog
-rw-rw-r-- 1 dgraph dgraph          0 Sep 11 10:08 053522.sst
-rw-rw-r-- 1 dgraph dgraph     255570 Sep 11 10:07 MANIFEST
-rw-rw-r-- 1 dgraph dgraph   56354220 Sep 11 10:07 053521.sst
-rw-rw-r-- 1 dgraph dgraph   56511107 Sep 11 10:06 053520.sst
-rw-rw-r-- 1 dgraph dgraph 1073741921 Sep 11 10:05 001217.vlog
-rw-rw-r-- 1 dgraph dgraph   72248682 Sep 11 10:05 053519.sst
-rw-rw-r-- 1 dgraph dgraph   72701342 Sep 11 10:05 053518.sst
-rw-rw-r-- 1 dgraph dgraph   72701334 Sep 11 10:05 053517.sst

root@data-graph01:/data/dgraph/contactlist_graph/p# ls -lt | tail 
-rw-rw-r-- 1 dgraph dgraph 1073741980 Aug 21 18:00 000138.vlog
-rw-rw-r-- 1 dgraph dgraph 1073742051 Aug 21 18:00 000315.vlog
-rw-rw-r-- 1 dgraph dgraph 1073742022 Aug 21 18:00 000067.vlog
-rw-rw-r-- 1 dgraph dgraph   72701329 Aug 21 18:00 017330.sst
-rw-rw-r-- 1 dgraph dgraph 1073742798 Aug 21 18:00 000047.vlog
-rw-rw-r-- 1 dgraph dgraph 1073756877 Aug 21 17:59 000097.vlog
-rw-rw-r-- 1 dgraph dgraph 1073742061 Aug 21 17:59 000414.vlog
-rw-rw-r-- 1 dgraph dgraph 1073742079 Aug 21 17:59 000398.vlog
-rw-rw-r-- 1 dgraph dgraph 1073741979 Aug 21 17:59 000201.vlog
-rw-rw-r-- 1 dgraph dgraph 1073741962 Aug 21 17:59 000193.vlog

From my observation, more and more vlog were generated while the oldest vlogs were still here. This explains quite well why more and more disk were consumed.

**Comment by manishrjain** [comment]
We should run the GC more often than every 10 mins. It should be run for every GB of data that's added in Badger, and also periodically.

**Comment by pawanrawal** [comment]
With the change in 27c3ddb6abdb81fc6add6edb28a2a19ef25f1d9c we run GC for every GB data of data added to badger and also every 10 mins.

**Comment by 315445896** [comment]
The same situation was found after v1.0.2(v1.0.3-v1.0.5). v1.0.0-v1.0.2 is OK.

**Comment by manishrjain** [comment]
@315445896 : Maybe try with master. I've made a bunch of changes to Badger, and pulled it in.

**Comment by 315445896** [comment]
@manishrjain Thanks for your reply.I have tested the nightly version.The number of vlog files increases, but the size of a single file becomes smaller.It crashes after about 10 minutes(probably because of GC?). 
I just keep inserting and deleting data( dgraphClient.alter(Operation.newBuilder().setDropAll(true).build()) )  in loop through a java client.

goroutine 26696815 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/skl.(*Skiplist).findNear(0xc055e2ed00, 0xc05b4031d0, 0x24, 0x30, 0xc042070100, 0xc04fd636e0, 0x1)
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/skl/skl.go:209 +0x315
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/skl.(*Skiplist).Get(0xc055e2ed00, 0xc05b4031d0, 0x24, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/skl/skl.go:376 +0x97
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).get(0xc04207a380, 0xc05b4031d0, 0x24, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:501 +0x124
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc04cfbc370, 0x101608e8a, 0x39, 0x7e9e7176, 0xc05154fde0, 0x0, 0x0)
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:169 +0x54d
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Item).prefetchValue(0xc04cfbc370)
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:188 +0x3c
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Iterator).fill.func1(0xc04cfbc370)
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:509 +0x32
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Iterator).fill
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:511 +0x28e

**Comment by manishrjain** [comment]
Dropall is mostly meant to be used in feature testing, etc. I wouldn't recommend using it for anything realistic.

Can you instead insert and delete data using normal transactions and stuff?

**Comment by 315445896** [comment]
You are right.It's normal when only using transactions.Thx!

**Comment by manishrjain** [comment]
As I said, you can use DropAll. Just use it sparingly. DropAll is not a transactional API. It has to stop everything and then delete everything. It's almost like a hack that we put in place to make it easier to interact. There's no way to get that data back, you can't just roll back a drop all command.

**Comment by dkirchhof** [comment]
I'm a bit confused. My empty database takes up to 2gb of disk space. Why is it so big?
