### ISSUE TITLE
AgensGraph vs Dgraph

### ISSUE THREAD

**Issue by candysmurf** [dgraph-io/dgraph#1435]
Dear Dgraph,

I would like to hear your expert views of AgensGraph vs Dgraph pros and cons.

There is a bench mark about [agensgraph vs neo4j](http://www.businesswire.com/news/home/20170629005344/en/Graph-DBMS-Performance-Comparison-AgensGraph-vs.-Neo4j).

Thanks

**Comment by pawanrawal** [comment]
Hi @candysmurf 

We are currently setting up the benchmark suite for Dgraph so that we can run the LDBC Social Network benchmark. Once we have that up we could compare against AgensGraph as well. Expect that in a couple of weeks.

**Comment by candysmurf** [comment]
@pawanrawal, I'm on vacation this week. I'll probably need to compare Dgraph and AgensGraph next week once I'm back. We need to have our selection soon. It's great to know that you're setting up the benchmark suite. If you have any progress, would you please update me? thanks.

**Comment by manishrjain** [comment]
Hey @candysmurf ,

LDBC benchmarks require us to update our Java client, and add an LDBC driver etc., which would take some dedicated effort as well. We were trying to set up the benchmark suite for Social Network Benchmark, but ran into multiple issues because the framework wasn't correctly set up and we couldn't get any help from the folks who created the framework.

This isn't high priority for us, so we can't afford to put an engineer on this right away, but will do so in the near future.

Some time ago, we had run benchmarks against Neo4j, based on Freebase film data, which you can refer to here: https://blog.dgraph.io/post/benchmark-neo4j/

Also, from what I understand, AgensGraph runs on a single server, is a multi-model database and provides ACID transactions. Dgraph is designed to be horizontally distributed, native graph database to provide low latency, high throughput query traffic in a real world cluster, and doesn't support transactions. The design goals of these two databases are very different. I think your decision would come down to what features you're looking for when comparing these two databases. Performance, horizontal scalability, or ACID transactions.

Performance, sharding, and simplicity of design are *very* important to us -- it's something we aim for rigorously. If that's something you're looking for, Dgraph is a good choice.

**Comment by candysmurf** [comment]
@manishrjain, understood. thanks for your inputs.

**Comment by manishrjain** [comment]
Hey @candysmurf , curious how was your experience with Dgraph and Agensgraph. Anything we could improve upon?

**Comment by archenroot** [comment]
@candysmurf - same here, any results from your observations?
