### ISSUE TITLE
Port over existing test cases for system tests

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1536]
- Port over the test cases from `contrib/goldendata-queries.sh`
- Port over the test cases from `https://docs.dgraph.io/query-language/`

**Comment by manishrjain** [comment]
Looks like this is similar to the task that you were looking at, i.e. pick queries from docs and make them part of our testing suite.

**Comment by campoy** [comment]
This is similar to #3987 although not necessarily the same.

This issue is about moving those queries into our test suite, while #3987 is about running those queries on the playground frequently to detect any breakages (on the code, the dataset, or the playground).

**Comment by danielmai** [comment]
[./systest/21million](https://github.com/dgraph-io/dgraph/tree/c3a3e9cc2650f27da9165a07d4851664d248a55b/systest/21million) runs in CI for every PR. The tests verify both [21-million movie data set](https://github.com/dgraph-io/benchmarks/blob/master/data/21million.rdf.gz) bulk loading and a variant of queries from the docs modified for tests. Unlike the doc queries, the systest queries don't assume the same UIDs across runs since the data set has blank nodes. Specifically, the queries in systest:

1. Omit `uid` in query responses
2. Omit queries using UID literals (e.g., `uid(0x1234)` or `after: 0x1234`)

This way,  test cases only need to check for equivalent values since UIDs can change across runs when blank nodes are auto-assigned UIDs during the loading process.

I'll close this issue since these queries are covered in systest now, and keep #3987 for specifically testing the published version of https://docs.dgraph.io, which is testing correctness of Play and docs vs Dgraph itself.
