### ISSUE TITLE
Is there a way to update Dgraph without erasing / removing the data?

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph#1605]
Everytime I update Dgraph, all the data is lost so I always have to export it, and import it after the update completed. It's fine as I only have thousands of nodes and predicates right now.

But once my tests are more or less over, loading the full data will include millions of nodes and even more predicates. Making it hard to export / import at every update.

Thanks!

Lazhar

**Comment by pawanrawal** [comment]
Hey @lazharichir 

We are still pre 1.0 and in trying to optimize things for the user we sometimes change the data representation on disk because of which you have to reload the data. That being said, once we reach `v0.9` which should be in another 2-3 months you can expect that you won't have to reload data after every release.

**Comment by amandalmia14** [comment]
@pawanrawal is the feature 'update' is been added in the latest version of Dgraph ? Where one can update the Dgraph database without erasing the existing data.
