### ISSUE TITLE
Dgraph vs Janusgraph comparison ?

### ISSUE THREAD

**Issue by kavink** [dgraph-io/dgraph#1624]
Anyone from the community have a quick summary of features/differences and benchmark of DGraph vs JanusGraph?

And what is a biggest database in terms of size deployment for Dgraph either production or testing for scalability ?

**Comment by manishrjain** [comment]
We haven't run any benchmarks against Janus Graph, but various users (on Slack) who have worked with Janus graph find Dgraph to perform a lot better.

There're some new instances where Dgraph has been put into production, better to ask on the Slack channel and see if you could talk to some of those folks.

**Comment by lazharichir** [comment]
@kavink JanusGraph is the other graph database I am testing for my project. And I must say, it is still very much undecided. Dgraph so far wins in simplicity and execution time: it's fast and well-built. JanusGraph has some very much needed features that are bothersome when missing ([edge label multiplicity](http://docs.janusgraph.org/latest/schema.html#_edge_label_multiplicity) and [key cardinality](http://docs.janusgraph.org/latest/schema.html#property-cardinality) for example.

The comparison is perhaps premature since we have to wait perhaps until a more stable and advanced version of both graph databases to see what they have to offer with a fuller set of features.

**Comment by kavink** [comment]
@lazharichir Thanks, Can you let us know which one you finally chose, when you go "live" with your project in "production". And maybe after some bake time on how it did.. Would be a good blogpost too 👍

**Comment by lazharichir** [comment]
@kavink sure, I shall do! Honestly, I love Dgraph and even the team is very much hands-on and always helpful. It's just some practical features that I am finding myself struggling to do without. Let's see :)

**Comment by manishrjain** [comment]
@lazharichir : The features Dgraph is missing is exactly the kind of feedback we need. I think key cardinality is something that we kinda already do, but plan to fortify in the future releases.

**Comment by lazharichir** [comment]
@manishrjain totally agree but then I also understand that you guys have a lot on your plate and you cannot just execute upon any feature request which completely makes sense _(e.g. edge label multiplicity as per [this thread](https://github.com/dgraph-io/dgraph/issues/1649))_

**Comment by Textras** [comment]
In making this decision, is there a direction/reference you can point us too regarding long-term enterprise costs for Dgraph? What's the monetization plan, like Neo4j?

**Comment by manishrjain** [comment]
All current Dgraph code is open source. So, the costs would be the engineering effort required to manage a Dgraph instance, which we're continuously improving to keep it down. We don't have any cost estimation done at our end.

For monetization, we'll start adding proprietary features next year and plan to run Dgraph as a service.
