### ISSUE TITLE
Performance and Type Safety - Protobuf vs JSON

### ISSUE THREAD

**Issue by Brahmasmi** [dgraph-io/dgraph#1784]
The latest version seems to use only JSON for client serialization (https://github.com/dgraph-io/dgraph/commit/d5ed6fcbc83e6b83630a5ee490aba1152b2e025e). Could the good volks here expound on the reason to shift from protobuf to JSON?

This decision impacts two aspects - Performance and Type Safety. The performance aspect is outlined in this blog post - https://blog.dgraph.io/post/protobuf/. JSON and type safety don't exactly go together.

IMHO, forcing JSON on all clients seems like a fatal regression. I would request the team to please reconsider this decision to impose JSON and to continue to prefer protobuf.

**Comment by manishrjain** [comment]
Hey @Brahmasmi ,

You bring up two important points. Let me deal with them first.

1. Performance: We wrote that post before we worked on various things to improve JSON marshal performance. We were using Go maps and then marshaling them to JSON before, which was expensive and slow. Then we made a change to write serialized version of JSON directly to a byte buffer, so marshal became really cheap. We then improved it further with a string of updates over time. So, JSON marshal is cheaper and faster than generating a lot of small Go structs required to create a Proto, and then marshaling it.

2. Type Safety: Type safety is a great feature of PBs. However, it doesn't apply in this case. We have no idea about users' data structures. All results from Dgraph come with a generic node and edge structure, and then have to parsed into Go or language structs, which requires complex code to do the conversion.

On top of these, no one was using PBs because of how strange they looked when formulating subgraphs. Most folks were using JSON anyway, because it is the lingua-franca of the web.

By getting rid of PBs, we decreased our code base by 4000 lines. See this: https://github.com/dgraph-io/dgraph/commit/d5ed6fcbc83e6b83630a5ee490aba1152b2e025e

Also, every language client now doesn't need to have a special PB to struct converter. They can use JSON directly, and every language has a really good support for JSON.

I hope this sheds some light on why we decided to eliminate PB from client-side communication, and double down on JSON.

**Comment by MateusAmin** [comment]
protobuf interoperability would be nice. For example, if I could export a granular subset of the entities and types in dgraph schema to protobuf. This way I could use the dgraph schema as a source of truth.

Right now, what ends up happening in my application is that I maintain a few scatter protobuf entities that shadow the database entities. 

Taking a step back data and relationships, which I will just call entities, are defined in protobuf files, in code (in different languages), and in database.

- For the entities that are codebase specific defining them in language works. 
- For entities in dgraph the dgraph schema works
- For entities shared across code bases protobufs work
- For entities shared between codebase and dgraph ?????

So I have a subset of entities maintained in code and dgraph schema. Ans then a subset maitnained in protobuf and degraph schema. Outside dgraph I would otherwise never need to maintain two mirrored definitions.

Hence, a story around this would be nice. This is the first google result when searching protobuf + dgraph and is from 2017. I hope someone comes here and tells me that there is already a good way to managed this.

**Comment by MateusAmin** [comment]
On the other hand the shared entities typically have stricter subset when talking about communicating A to B. Where A and B would be codebases, databases, etc. So the above would be an over optimization. However, I am still open to suggestions. 

Ideally, It would be nice to define them generally. And then export stricter subsets for each specific use. Which would probably need to be an agnostic language more global then a protobuf or database schema... 

From a rust perspective I could probably do this with rust macros and attributes. Probably, not worth the effort however.

**Comment by MateusAmin** [comment]
It terms of json performance Levien’s comments here on point: https://raphlinus.github.io/xi/2020/06/27/xi-retrospective.html

And I there are ways to achieve type safety in JSON. 

But it is really more of matter practical matter of usability where  performance, and typesafey are a subset. JSON ubiquity make it a pretty clear winner for tooling if you had to pick one. However, seems like protobuf support could be an enterprise feature? *shrug*
