### ISSUE TITLE
uid field is returned in the result even if said uid does not exist in the database.

### ISSUE THREAD

**Issue by sjama** [dgraph-io/dgraph#1811]
Given this query 

```
{
  user(func: uid(0x9665656)) {
    uid
    name
  }
}
```
the result will contain the uid and name if the user exists but will still contain the uid if the user does not exists.

This is unhelpful behaviour because an empty array will aid in triggering  “a user not found error”. 
In this instance I am using the name field to determine if the user exists or not.

**Comment by peterstace** [comment]
Dgraph doesn't have a concept of presence or absence of nodes. Nodes are stored implicitly (always as part of edges) rather than explicitly.

If the name attribute isn't found, then the name won't be populated in the response, telling you that the user doesn't exist. Another way to do this directly in the query is to use a filter. E.g.

```
{
  user(func: uid(0x9665656)) @filter(has(name)) {
    uid
    name
  }
}
```

PS: I'm curious, how did you get the UID 0x9665656 if it doesn't exist in the graph?

**Comment by sjama** [comment]
I discussed this with @pawanrawal via slack and reckon's it's possible to remove uid without children from the result. 

Regarding the uid, It's just random number I typed  which is based on 0x9f6 a valid uid that does return a result.

**Comment by pawanrawal** [comment]
We discussed it and reckon that it's going to require special handling which might not work well for certain scenarios. This is because the system isn't designed that way as @peterstace mentioned.
