### ISSUE TITLE
Use ratel without internet access

### ISSUE THREAD

**Issue by cilier** [dgraph-io/dgraph#1992]
I am building a dgraph cluster without internet access, but when I opened ratel, it was blank. I asked about it in slack, pawan told me that ratel need Amazon to download the css and js files.Could you package these files in the binary file, or do something else to ensure that I can use ratel without internet access?

**Comment by commesan** [comment]
There are plenty of company environments that want to use these kinds of tools on systems without internet access. Especially with the ever growing security concerns that come with having private data on internet connected machines. 

Besides that. I would prefer predictable and stable releases with all dependencies baked in. Instead of something that grabs stuff from the internet leaving it vulnerable to all kinds of tampering.

People who want and need the latest changes and updates can build from source. But the releases should be idempotent.

**Comment by ljwh** [comment]
@commesan , I met this problem too today, and I think you can do like this:
 1. open the localhost:8000 page which you can not load in intra-net, and save as html file.
 2. find out which js or css files you can not download, and download these with public internet connection.
 3. move these js and css files to intra-net.
 4. replace these js and css links in html file(from step1) with local js and css file locations.
 5. open html file with your browser.

Hope it works.

**Comment by commesan** [comment]
@ljwh , thanks for the tip on the work-around. That seems to do the trick. 

Still I would prefer it if the libs were packaged. The security concern and deploy-ability will certainly will weigh in when considering adoption.

**Comment by manishrjain** [comment]
We have found that being able to modify JS and CSS files on the fly is very helpful in iterating on Ratel, which is largely a UI/frontend software. At least for now, we don't have plans to package these files up together with the binary.

On a tangential note, we have plans to make the code of Ratel be open (without necessarily being open source), which would allow users to change things as they deem fit.

**Comment by paulftw** [comment]
Ratel v1.0.8 will have an ability to run from local packaged JS. A user is given an option to use packaged version when they open ratel w/o internet access
