### ISSUE TITLE
Conflicts when ignoring index conflicts

### ISSUE THREAD

**Issue by Levatius** [dgraph-io/dgraph#2091]
Hi again,

I have built a script ([simple_mutates.zip](https://github.com/dgraph-io/dgraph/files/1696287/simple_mutates.zip)) that performs a simple mutate on a single node several times per transaction. With Python 3.6, please run **python main.py** in two terminals.

There are a few questions raised by its behaviour: 

1. With **ignore_index_conflict** set as **true**, we observe that transactions between the two processes are still able to conflict (on average ~3% of transactions conflict). Why might this be?

2. With **ignore_index_conflict** set as **false**, surely every transaction should conflict; this is not observed however (on average ~8% of transactions conflict). Again, I am unsure why not.

3. Slightly unrelated but I have noticed that the amount of memory that my local dgraph server uses slowly increases even though there is only a single node in the graph. I don't really see why this would happen.

Thanks in advance.

**Comment by Levatius** [comment]
@jimanvlad

**Comment by pawanrawal** [comment]
Couldn't get to this today but I'll have something on this for you tomorrow.

**Comment by pawanrawal** [comment]
A transaction can have conflicts because of data keys and index keys. When you do the following mutation while also having an `exact/hash` index.

```
<1> <xid> "alpha" .
```
The data key is something like `1_xid` and the index key is something like `alpha_xid`. 

1. So even if you have IgnoreIndexConflict as true, data keys still might conflict and you could get the error since you are trying to modify the same `uid`. If you changed it to a blank node and IgnoreIndexConflict is true, then you would not have any conflicts.

2. With `IgnoreIndexConflict` is false, I do see almost every transaction conflicting. I ran the Go program below and only one of the clients was able to commit its transactions and the others (3 more) were ending up with errors for every transaction (either in Mutate or in Commit).

3. What was the initial memory and what does it increase to? We store some meta data about transactions so that might be increasing the memory.

[main.go.gz](https://github.com/dgraph-io/dgraph/files/1709377/main.go.gz)

**Comment by pawanrawal** [comment]
@Levatius @jimanvlad ^

**Comment by Levatius** [comment]
This has been helpful information, we are now thinking about splitting our nquads by predicate and having each process accept an exclusive subset of the predicates to mutate on. This way, we should avoid collisions on the data keys while still getting a decent level of concurrency.

**Comment by pawanrawal** [comment]
The issue can happen while creating new nodes because of `IndexConflicts`. You could try using `IgnoreIndexConflicts` if not doing upserts.

**Comment by calummoore** [comment]
I do have that setting switched on - and I'm still getting aborts (Dgraph Node library turns it on automatically).

So this is the code that gets run - 

```
const txn = client.newTxn()
const mut = new Mutation()
mut.setIgnoreIndexConflict(true)
mut.setCommitNow(true)
await txn.mutate(mut)
```

**Comment by calummoore** [comment]
@pawanrawal Any update on this? I'm still getting this error when ignoreIndexConflict is true and I'm creating new nodes.

**Comment by pawanrawal** [comment]
Hey @calummoore sorry I couldn't figure out how to run the test when I looked at this initially. Pardon my Javascript ignorance. For anyone else looking to run it, you can call this command from the root of the repo after changing `xit` to `it` at https://github.com/calummoore/dgraph-node/blob/master/src/__tests__/load.spec.js#L17.
```
node_modules/jest/bin/jest.js -t 'should not abort'
```

So these aborts happen because all the different concurrent updates are trying to modify the same data key because of this statement.
```
<${siteId}> <site.customers> _:cust_${i} .
```

Since `siteId` is fixed for a test and all mutations are trying to write to the data key `<siteId> +  <site.customers>`, hence most get aborted. This would not happen if `siteId` were different.

**Comment by calummoore** [comment]
@pawanrawal - Yes, sorry I should have mentioned that!

I understand the reason for aborting on primitive key updates (`string`, etc), but what's the reason behind aborting for a posting list (which is effectively a `set`) update? 

I can't think of a scenario where there would be a clash for simultaneous `set` mutations, especially with index conflicts turned off? If the key is already part of the set, then nothing changes, if it's new it is added - so multiple requests to add the key do not conflict.

Also, I was able to get the simultaneous run rate by swapping around the key ownership and using a reverse index - which seems to suggest it should be possible the other way around?
```
_:cust_${i} <customers.site> <${siteId}> .
customers.site: uid @reverse .
```
Instead of
```
<${siteId}> <site.customers> _:cust_${i} .
```

**Comment by janardhan1993** [comment]
For most of the use cases, I think aborting at posting list level is not required. We will do a change to allow user to add different uid to same posting list without conflict.

**Comment by janardhan1993** [comment]
I have opened a new issue to track this #2221

**Comment by payne4handsome** [comment]
@pawanrawal Hello, I can't find IgnoreDataConflict option in latest version v20.07. I used java client api. maven dependency is 
```
 <dependency>
            <groupId>io.dgraph</groupId>
            <artifactId>dgraph4j</artifactId>
            <version>20.03.2</version>
        </dependency>
```
