### ISSUE TITLE
performance issue with tutorial

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [dgraph-io/dgraph#2095]
when I imported movies list(https://tour.dgraph.io/moredata/1/), it ate 1 core for a couple of hours, with next messages:
 2018/02/06 16:21:42 lru.go:79: LRU cache max size is being set to 50 MB
2018/02/06 16:21:52 lru.go:79: LRU cache max size is being set to 50 MB
2018/02/06 16:22:02 lru.go:79: LRU cache max size is being set to 50 MB
2018/02/06 16:22:12 lru.go:79: LRU cache max size is being set to 50 MB
2018/02/06 16:22:42 lru.go:79: LRU cache max size is being set to 50 MB
2018/02/06 16:22:52 lru.go:79: LRU cache max size is being set to 50 MB

db folder took ~500MB, so I must stop it, not sure if this is correct behavior ?

**Comment by pawanrawal** [comment]
> 2018/02/06 16:21:42 lru.go:79: LRU cache max size is being set to 50 MB

This log doesn't indicate any performance issue. It has been removed in master.

> it ate 1 core for a couple of hours

The current release has an issue where high CPU usage has been observed even when Dgraph is sitting idle. It has been fixed in master and would be part of next release (happens this week).

> db folder took ~500MB

Dgraph tries to do garbage collection when the value log size exceeds 1 GB. So it will eventually decrease if there are duplicate values as your database size increases.

**Comment by pawanrawal** [comment]
The first two issues should be resolved in the latest release.

**Comment by vitaliy-kuzmich** [comment]
thanks a lot for fast responses.
