### ISSUE TITLE
Support arbitrary-precision numeric types

### ISSUE THREAD

**Issue by malzzz** [dgraph-io/dgraph#2107]
My use-case for dgraph deals almost exclusively with 256-bit uints.  Are there any plans for bignum datatypes at any point in the future?  If not, is there possibly a way to implement that myself as a plugin?  There are some workarounds I can use, like storing raw representations as strings, but none of those are ideal, since they'd limit the range of possible queries.  Thanks!

**Comment by pawanrawal** [comment]
We may support them later but it's not a priority right now since there isn't enough demand for it. Adding support is non-trivial since Go doesn't support these types natively.

**Comment by srfrog** [comment]
Related: #926

**Comment by manishrjain** [comment]
We can switch our implementations to this. Or, introduce a new type for arbitrary-precision numeric types:

https://golang.org/pkg/math/big/

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8746). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by CaelumF** [comment]
I'm surprised there isn't demand for it. It is essential for anything related to money or crypto. One lovely thing about dgraph is that I can use the very same Kotlin classes that my backend uses with [graphql-kotlin](https://github.com/ExpediaGroup/graphql-kotlin) after they're converted to GraphQL automatically for persistence, runtime and the frontend! But because dgraph doesn't support BigDecimal I'd have to change the frontend and backend to work with some seriously unsavoury alternatives (made worse by the large difference in value between currencies) :(

**Comment by aranwe** [comment]
Yeah, I would love to see this in Dgraph too. Any chance of reopening/revisiting this? I can imagine that this brings a lot of complexity. :)

**Comment by sanudatta11** [comment]
Hello, Any update on having this integrated? This will be a serious boost in our decision to use DGraph in our upcoming financial services
