### ISSUE TITLE
Spark connector for Dgraph

### ISSUE THREAD

**Issue by jimanvlad** [dgraph-io/dgraph#2123]
Hi,

It would be great if, at some point, a Spark connector was to be created.

Neo4J uses its connector both for preprocessing and loading data in, but also to get sub-graphs out for processing in Spark.

https://neo4j.com/developer/apache-spark/
https://spark.apache.org/docs/0.9.0/graphx-programming-guide.html

Vlad

**Comment by EshwarSR** [comment]
Hi. I'm also looking for such a feature. I guess many people will be benefitted by this.

For now, is there any way to get this done faster than querying all the data from dgraph and populating the spark dataframes?

**Comment by srfrog** [comment]
Damn, sorry for the wrong reference. Butter fingers

**Comment by EnricoMi** [comment]
I am currently looking into this. I have created a very simple connector that can load data from DGraph into Spark. I have a few fundamental questions / requirements to get to a robust solution.

Spark is a massively parallel cluster where hundreds or thousands of concurrent reads would hit the DGraph cluster. For this to work the Spark connector 1) needs to know the exact partitioning and available alphas existing in DGraph, and 2) needs to be able to query / read non-overlapping and deterministic parts (partitions) of the data. Is there a way to get access to the partitioning and cluster setup through the grpc endpoint? What I would need is the groups, the predicate range per group and the alphas per group. Would I at al be able to query a given alpha directlyl? Handling a change of this partitioning will be challenging.

The next thing is to be able to read fraction of the graph. Lets consider two use-cases: I) read the entire graph and II) given a GraphQL query, read the entire result set. For each of these use-cases there needs to be a way to retrieve a fixed fraction (in Spark called a partition, not 1:1 a DGraph partition, but for simplicity and performance a Spark partition is a well defined subset of a DGraph partition). How could I read a single partition of DGraph data? Simplest approach would be `has(PROPERTY)` for the set of properties in a partition.

Spark partitions are immutable. Can we, for the lifetime of a Spark partition that is mapped to a DGraph partition, guarantee we see an immutable graph / a snapshot?

In use-case II), a Spark partition is not mapped to a DGraph partition anymore, because the data  potentially come from multiple DGraph partitions already. How could the result set be split into Spark partitions? With pagination? That would require to know the exact number of results in the first place. The result `uid` space could be split into partition ranges. Are range queries like `0x1 <= uid < 0x9` supported and efficient on an arbitrary GraphQL query? Can I get the space of possible `uid`s / the min and max `uid` existing in the DGraph?

Finally, given a single Spark partition ideally is in the order of 1 million rows / predicates / triples, a streaming JSON result from grpc would be desirable. Using the example of the official Java client, `client.newReadOnlyTransaction().query(query)` loads the entire response JSON into memory, then parses it into a JsonObject or something alike before I can provide it to the iterative Spark API. Does the grpc support a JSON stream? Do you know if the Java client supports that stream of results if grpc does?

**Comment by EnricoMi** [comment]
inviting @mangalaman93

**Comment by danielmai** [comment]
Hey @EnricoMi. It's great to hear you're looking into Spark and Dgraph integration.

> Is there a way to get access to the partitioning and cluster setup through the grpc endpoint? What I would need is the groups, the predicate range per group and the alphas per group.

You can check Zero's /state page for cluster membership info. ([docs](https://dgraph.io/docs/deploy/#more-about-state-endpoint))

> How could I read a single partition of DGraph data?

You can use queries to retrieve a specific subgraph of your dataset.

> Can we, for the lifetime of a Spark partition that is mapped to a DGraph partition, guarantee we see an immutable graph / a snapshot?

Dgraph has transactions. So, you can create a new transaction, and queries within that transaction will be for a snapshot of the data at a particular timestamp.

> Can I get the space of possible uids / the min and max uid existing in the DGraph?

In /state there's a field called `maxLeaseId`. That would be highest possible UID that could be in Dgraph at that moment. i.e., the maxLeaseId could be `10000` but the actual highest UID already assigned to a node could be `123` and definitely not 10001.

> a streaming JSON result from grpc would be desirable

Queries currently aren't streamed. If this is something you need, please file a separate feature request.

**Comment by EnricoMi** [comment]
Hi @danielmai, thanks for the pointers!

How does the concept of subgraphs work in DGraph? Can you point me to docs or examples? Can you elaborate on that a bit more?

The rest is clear and gives me a lot to work through. I'll let you know how it goes or if I need something else.

Enrico

**Comment by EnricoMi** [comment]
I have released the first version of the Spark Dgraph Connector as `uk.co.gresearch.spark:spark-dgraph-connector_2.12:0.1.0`. It is for Spark 3.0. I will back-port it to Spark 2.4 this week.

The connector provides partitioning by predicates and uids. I have a few questions on what you think about the specific implementation of partitioning, especially regarding efficiency and scalability towards large graphs (billion of nodes / edges / properties) and large schemata (millions of predicates).

# Transactions

Central to the connector is to have all partitions read at the same transaction Ts. The problem I am facing here is that the user application can determine / create a transaction, but Spark partitions have to use that transaction for their query on different machines / in different processes. How can I get the transaction Ts from the user application and then use it with the client on the Spark nodes?

# Predicate partitioning

The main motivation for predicate partitioning in a multi-group cluster is to read only those predicates from alphas that are stored locally. Once loaded into the Spark cluster, Spark will shuffle the data around anyway in the form needed. This avoids Dgraph cluster internal communication, as no alpha needs to fetch predicates from alphas of other groups. Would you say, avoiding Dgraph internal communication is a good optimization goal, given the cluster gets hit by hundreds or thousands of Spark workers (partitions) to fetch the entire graph? In a multi-group Dgraph cluster and without predicate partitioning, the number of connections induced within the Dgraph cluster might be equal to the number of spark workers connecting to the cluster multiplied by the number of Dgraph groups.

A partition would issue the following query to its dedicated alpha:

    {
      result (func: has(dgraph.type)) @filter(has(prop1) OR has(prop2) OR has(edge1) OR has(edge2)) {
        uid
        prop1
        prop2
        edge1 { uid }
        edge2 { uid }
      }
    }

Since `OR` cannot be used in `(func: has(...))`, it has to be added via `@filter`. Do you see a performance issues with this approach (assuming billions of nodes / edges, or millions of predicates), or a better way to retrieve a given set of predicates only? Millions of predicates can be split into 1000-predicates partitions. Dgraph seems to be very quick parsing such large queries with 10k predicates (though most of them did not exist in the schema in my test setup).

# Uid partitioning

The most elegant way to partition the graph is by uid. I found pagination fit in here very well:

    {
      result (func: has(dgraph.type), first: 500, offset: 0) {
        uid
        expand(_all_) {
          uid
        }
      }
    }

Provides me with the first 500 existing uids in ascending order, all their properties and edges. What do you think about this approach? How does pagination scale? Is it constant or linear with the "page number", e.g. is `first: 1000, offset: 1000000` as fast as `first: 1000, offset: 0`?

With this I can easily split the `maxLeaseId` space into even sized chunks. Some partitions might end up being empty but `maxLeaseId` is a good and quick estimate for the number of uids in the graph.

However, I would prefer to run this query first to get the exact number of uids in the graph:

    {
      result (func: has(dgraph.type)) {
        count(uid)
      }
    }

Predicate and uid partitioning can easily be combined, so count would look like this with predicate partitioning present:

    {
      result (func: has(dgraph.type)) @filter(has(prop1) OR has(prop2) OR has(edge1) OR has(edge2)) {
        count(uid)
      }
    }

This counting provides me with the exact number of uids having any of the predicates. Can you tell me how costly this query would be on a very large graph with multiple groups?

Btw., I can use pagination to stream results into one partition as well, which makes the streaming Json discussed above redundant.

# Property filtering

For a specific use case I need to fetch all predicates that are no edges:

    {
      result (func: has(dgraph.type)) {
        uid
        expand(_all_)
      }
    }

The `expand(_all_)` here expands only predicates that do not lead to uids. Is there an equivalent way to get predicates expanded that *do* lead to uids only?

# Alpha resilency

For resilience, each partition uses its dedicated alpha and falls back to the other alphas of the group if the dedicated alpha is not available. Dedicated alphas get assigned to partitions in a round-robin fashion.

# String lang

I could not find a way to retrieve all string predicates of a node that have language tags. The `expand(_all_)` does not expand to those strings. Do you see a way to retrieve those with current Dgraph capabilities predicates (other than explicitly mentioning the predicates)?

# Facet types

Finally, could also not find a way to retrieve the type of facets. They are typed on write (RDF types), but the Json response gives me only some indication of typing as Json does not support all Dgraph types. Is there a way to retrieve the types of facet values with current Dgraph capabilities?

**Comment by danielmai** [comment]
Thanks for sharing, @EnricoMi! I've created PR #5859 to add your Spark connector to the docs.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8867). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
