### ISSUE TITLE
Q: Servers, replicas, groups, shards, and tablets. Do I understand this correctly?

### ISSUE THREAD

**Issue by politician** [dgraph-io/dgraph#2171]
Can you check my understanding of the relationships between servers, replicas, groups, shards, and tablets described in the documentation?

1. A _cluster_ is the entire deployment of a dgraph instance. A cluster contains at least one server, at least one zero, and zero or more RAFT quorums.
2. A _zero_ is a super node. It monitors and balances the data held on servers.
2. A _server_ is a worker node within a cluster.  It contains the actual data on disk, and serves both reads and writes. A server contains exactly one group.
3. A _group_ is a logical collection of predicates. A group contains at least one predicate.
4. A _predicate_ is a logical collection of ground truths.
5. A _tablet_ is a physical collection of ground truths stored on the disk. A tablet contains the physical data for one predicate.
6. The terms _shard_, _data shard_, and _tablet_ as used in the documentation are synonyms.
7. A _replica_ is a server that belongs to a distinct quorum.  Depending on the value of the `--replicas` flag all servers are replicas (`>=2`) or none of them are (`==1`).
8. A _quorum_ consists of a set of replicas that provide readwrite access to consistent copies of the exact same group where consensus is handled by RAFT. A quorum contains a least _two_ servers, but ideally 3 or 5 to avoid split brain situations.

**Capacity Planning**

The `--replicas` tunable applies to the entire cluster and not to a particular predicate.  To plan the number of servers for a cluster with `replicas > 1`, you have to be able to predict the number and size of predicates for your schema, and then solve a bin packing problem to estimate how many groups dgraph would optimally want to break that into.

When sizing a cluster, if you opt for few groups and large disks, you'll run into throughput issues on reads due to page faults.  Alternately, if you opt for more groups, then you'll have to provision redundant servers for predicates that see low query traffic resulting in higher TCO.

If I understand things correctly, maybe the thing to do here is to let folks set replica policy on a per predicate basis, and then let the zeroes migrate tablets based on policy rather than cluster-wide settings?

**Comment by politician** [comment]
In the absence of fine-grained tunables, it seems like the thing to do is to provision 5 servers and set `--replicas 5`, then pick the largest, fastest SSDs you can.  That way, you pay the price of RAFT consensus once, and can avoid the group/predicate optimization problem. Your graph no longer scales though as adding more than 5 nodes to a RAFT quorum isn't recommended (see the paper); you could choose 3 servers though, and kind of have small (1), medium (3), and large (5) deployment options.

**Comment by pawanrawal** [comment]
1. Sounds right.
2. Yes, right. Apart from rebalancing the data, it is also used for assigning UIDs and transaction timestamps.
3. Right, though it might be more appropriate to say that a server serves data for only one group.
4. Right. Though initially, a group may not contain any predicate.
5. A predicate is just the middle part in a `<Subject> <Predicate> <Object>/ObjectValue .` RDF NQuad. Dgraph shards data by a predicate. Therefore all data for a predicate must reside on the same server.
6. A tablet consists of all the data corresponding to a predicate, including all the indexes.
7. Sounds correct.
8. Sounds correct. Though note if replicas had the value `2` and you just brought up three nodes, then the third node would be the only server serving group 2. So it's not a replica.
9. I think the docs are a bit confusing with regards to a quorum. Quorum is the minimum number of nodes that must be present for writes to go through which is `n/2 + 1` if a group has `n` servers.

Yeah, the `--replicas` applies to the entire cluster.

> To plan the number of servers for a cluster with replicas > 1, you have to be able to predict the number and size of predicates for your schema, and then solve a bin packing problem to estimate how many groups dgraph would optimally want to break that into.

Since Dgraph moves tablets around different groups based on their size at regular intervals, you don't have to solve the bin packing problem.

> If I understand things correctly, maybe the thing to do here is to let folks set replica policy on a per predicate basis, and then let the zeroes migrate tablets based on policy rather than cluster-wide settings?

That sounds very complicated for the user. Since Dgraph tries to ensure that different groups serve similar sized data, that should be good enough.

**Comment by zero-master** [comment]
Thanks for the details.

Can you please also describe how the data is rebalanced?

If not, a few links would immensely help.

**Comment by politician** [comment]
@pawanrawal Thanks for the review.  I'm still not sure how I should go about sizing a cluster of EC2 nodes without more fine-grained tools for managing replicas, but your other answers were helpful.

**Comment by rahst12** [comment]
_"A predicate is just the middle part in a <Subject> <Predicate> <Object>/ObjectValue . RDF NQuad. Dgraph shards data by a predicate. Therefore all data for a predicate must reside on the same server. "_ If you were modeling Twitter followers, several hops out - wouldn't the predicate "follows" eventually fill the server?
