### ISSUE TITLE
memory_mb parameter is not strictly enforced and ignored

### ISSUE THREAD

**Issue by Graphpinto** [dgraph-io/dgraph#2211]
memory_mb parameter.  Suggests you set it to half available memory, but I've observed it frequenty uses more than half, making even that a bad suggestion.

**- What version of Dgraph are you using?**

**- Have you tried reproducing the issue with latest release?**

**- What is the hardware spec (RAM, OS)?**

**- Steps to reproduce the issue (command/config used to run Dgraph).**

**Comment by manishrjain** [comment]
Rename to `lru_mb`, maybe.

**Comment by Graphpinto** [comment]
@pawanrawal  -- Given that we decided on the naming change for this one, I'm assigning this to you. Feel free to re-assign.

**Comment by pawanrawal** [comment]
I have the change in a [branch](https://github.com/dgraph-io/dgraph/compare/pawan/lru-mb?expand=1). Since we are making this change which is going to break scripts for users, we should only merge this right before the next release. 

Also, it might be worthwhile using a default value as <half_ram>, as that is what we recommend to users anyway. I am not keen on keeping this flag as mandatory since it's value is not very well correlated to the total memory usage by the process which depends on a variety of other factors.

**Comment by pawanrawal** [comment]
This was merged to master and is part of `v1.0.5`.
