### ISSUE TITLE
Add IgnoreDataConflict option

### ISSUE THREAD

**Issue by janardhan1993** [dgraph-io/dgraph#2221]
If this option is set, users should be able to add different uids to same posting list in two different transactions concurrently without conflict.

**Comment by manishrjain** [comment]
Isn't this the same as no transaction? The change that @pawanrawal made with `upsert` directive in schema should already reduce the conflicts considerably.

**Comment by janardhan1993** [comment]
Some users want to add two different uids to a big data key without conflict. Say users is adding details of all friends in different transactions then they don't want transactions to be aborted when different friends are being added.

**Comment by manishrjain** [comment]
It is not clear to me when the transaction would conflict. What sort of data operation would cause a conflict, what's the granularity we're operating at. Need a bit more details here.

**Comment by calummoore** [comment]
The issue I've been facing is when I attempt to simultaneously add nodes to an existing node's posting list. For example, if I have an existing site (`0x1`) and I want to simultaneously add customers to that site - I will get aborts (even with  `IgnoreIndexConflict` setting active). 

```
<0x1> <site.customers> _:cust_1 .
<0x1> <site.customers> _:cust_2 .
<0x1> <site.customers> <0x4> .
...
```

As I'm only adding keys to a posting list, which is effectively a set operation, there is no need to abort. Also, as I mentioned in #2091, this works for reverse indexes already.

Rather than add a new setting, I think it would just make sense to have the existing setting (`IgnoreIndexConflict`) also apply to posting lists.

**Comment by pawanrawal** [comment]
I think in some cases we don't need the guarantees that transactions provide. For e.g. for an application like Facebook, it doesn't matter if two friends are added to the same `<person_uid> <friend>`  posting list and transactions need not abort. Though for other applications they might want to ensure that a person can just have `x` number of friends and transactions could help maintain that.

**Comment by akshaydeo** [comment]
Hey guys, when can we expect this in the main release.
This issue almost makes it unusable in case of dgraph being mutated by event processors.

**Comment by manishrjain** [comment]
The conflict keys now use the object UID as well. So, adding different UIDs to the same PL does not cause any conflicts.

**Comment by calummoore** [comment]
Great news! 👍
