### ISSUE TITLE
Question: graphql+- compare two values

### ISSUE THREAD

**Issue by omurbekjk** [dgraph-io/dgraph#2343]
I have a `Car` node with `wheels: int` and `is_broken: bool` predicates.

1) How can I query all cars if the number of broken cars is zero?
2) How can I count all broken cars and use it as a variable somewhere?

This query returns all `cars` let's say: 10, 
```
  query(func: eq(label , 'car'  )  ) 
  {
    name 
  }   
```
And this one returns cars that are broken, and there are `3` broken cars.
```
  brokenCars(func: eq(label , 'car'  )  )  @filter( eq(car.is_broken, true))
  {
    name 
  }   
```

I tried this, 
```
{
  query(func: eq(label, "car" )) 
   {
    cars as count(uid)
   }   
  
  query2(func: eq(label, "car")) @filter(ge( val(cars),1 ))
  {
    name
  }
}
```
**Cannot assign variable to count()**

**Comment by pawanrawal** [comment]
> How can I query all cars if the number of broken cars is zero?

Your question is a bit confusing. Are you looking for cars that are not broken?The query below should give you that.

```
query(func: eq(label , 'car'  ) ) @filter(NOT eq(car.is_broken, true)) {
    name 
}   
```

> How can I count all broken cars and use it as a variable somewhere?

To answer this question, I have to understand what is that you are looking for as a result?

**Comment by omurbekjk** [comment]
@pawanrawal  Partially yes. My query should print nothing if one of the car is broken. If there all the cars are not broken, then i should query all cars.

**Comment by pawanrawal** [comment]
I see, since variables can't be assigned to `count` for now, you have two options.

1. Just fetch the number of broken cars, if its zero, then fetch all cars in a separate query.
2. Fetch the number of broken cars and all cars in another query block. Read the value of the number of broken cars, if it's> 0 then ignore the cars. This does fetch more data than required but would give you what you want in one query.

Ideally, we can support variables on count and then the last query you mentioned should work. Though this would be different compared to other value variables as this count value cannot be associated with a `uid`, so isn't a straightforward change.

**Comment by omurbekjk** [comment]
@pawanrawal Can you provide examples? Because when i tried to use variable in another query, got error `Cannot assign variable to count()`.

**Comment by pawanrawal** [comment]
As I said variable cannot be assigned to `count`, please read the two options I mentioned carefully again.

**Comment by omurbekjk** [comment]
@pawanrawal I understood the first option you provided. 
Can you provide me simple example for **the second** option. 
I created two queries for fetching **broken cars** and **all cars**. Not sure how to read the value of broken cars. 

> Read the value of the number of broken cars, if it's> 0 then ignore the cars,

can you tell me about this more, better with examples?

**Comment by MichelDiz** [comment]
As this is a relatively old question, if you need more discussion. Please open a discussion in Discuss.
Also, It's interesting that the questions are asked there, to stay focused on bugs and features.

Cheers.
