### ISSUE TITLE
Question: Using the power of Bleve's search indexing to the fullest

### ISSUE THREAD

**Issue by dremekie** [dgraph-io/dgraph#2345]
Are we able to leverage Bleve's query syntax as described here?

http://www.blevesearch.com/docs/Query-String-Query

Or are we limited to `alloftext` and `anyoftext` queries as described here: https://docs.dgraph.io/query-language/#full-text-search

It would be extremely powerful to use its full query syntax.

**Comment by pawanrawal** [comment]
No, Dgraph doesn't support Bleve's query syntax. Only the functions mentioned at https://docs.dgraph.io/query-language/#functions are supported. Is there something specific that you are looking for which Dgraph can't do?

**Comment by dremekie** [comment]
Hi @pawanrawal I was looking for the ability to do wildcarding and/or fuzzy matching. But now that I've looked further, Bleve did not allow for that, the Lucene index does. Is there a way to do that? I'm thinking no?

**Comment by manishrjain** [comment]
We don't use Bleve indexing. We only use some libraries from there to help with tokenization etc.

We support regular expressions, but not fuzzy matching. If you need that, feel free to file an issue and explain your use case; so we can determine the level of priority.

2. You could do regular expression for your search, if ordering is important. Otherwise, you can do alloftext, and then do some filtering at application end.
