### ISSUE TITLE
live indexing is much more space consuming than bulk indexing

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2415]
if I provide schema with indexing when bulk loading, the bulk loaded data consumes around 500GB disk space; 
On the other hand if I omit indexing directive in bulk loader schema, and do the schema indexing alteration (identical to the one I would have provided for bulk loading) after the server is up and running, the server will work for several days creating the index until finally it consumes all of my disk space (3.2TB), and becomes unavailable and unfixable. 

This is possibly a performance issue, not very important since I can bypass it by doing indexing during bulk load. I'm just curious if you are aware of this issue

**Comment by xinstein** [comment]
I have the following 3 indexing predicates:

string @index(exact) .
int @index(int) .
datetime @index(datetime)

**Comment by manishrjain** [comment]
Can you try this with a clean state? Set the schema first and then do live loading.

**Comment by xinstein** [comment]
I've tried that route, it's unacceptably slow. But if for your debug purpose, I'll see if I can find an extra machine to test on.

**Comment by manishrjain** [comment]
I think what is probably happening is that the value log GC needs to catch up to the many versions of data points that get generated in the live loader -- because that route involves storing all the versions of the data as well. Bulk loading, OTOH, doesn't need to worry about intermediate data states, only the final one. So, it can produce the final clean slate without any version history.

This is expected. Over time, their space usage would converge.
