### ISSUE TITLE
can we assign Uid to the predicates that already exist using go client... ?

### ISSUE THREAD

**Issue by mettuaditya** [dgraph-io/dgraph#2450]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

- Have you tried reproducing the issue with latest release?

- What is the hardware spec (RAM, OS)?

- Steps to reproduce the issue (command/config used to run Dgraph).

- Expected behaviour and actual result.

**Comment by MichelDiz** [comment]
Hello Mettuaditya,

Predicates have no UIDs, only nodes.

If the question is about moving predicates to another already existing Node. The answer is no. The only way is rewirte a mutation to that existing UID/Node with the predicate data needed.

Please illustrate the question better because it was very vague. It would be ideal to talk about this at https://discuss.dgraph.io to leave the Github Issues feature free for more detailed issues. For productivity.

Cheers.
