### ISSUE TITLE
godoc DeleteEdges example

### ISSUE THREAD

**Issue by cloudmode** [dgraph-io/dgraph#2452]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
Dgraph version   : v1.0.5
Commit SHA-1     : 82787414
Commit timestamp : 2018-04-20 15:50:53 +1000
Branch           : HEAD

- Have you tried reproducing the issue with latest release?
It's latest, downloaded yesterday

- What is the hardware spec (RAM, OS)?
MacOSX, 32GB

- Steps to reproduce the issue (command/config used to run Dgraph).
https://godoc.org/github.com/dgraph-io/dgo#example-DeleteEdges

- Expected behaviour and actual result.
Fails with error:2018/06/20 11:41:52 rpc error: code = Unknown desc = Error while unmarshalling: [Riley Street] as geojson: invalid character 'R' looking for beginning of value

- Solution
		Location string    `json:"loc,omitempty"`
it appears that the 'loc' field expects it to be geojson value, not string
fix: change to:
		Location string    `json:"location,omitempty"`
Runs without error there

**Comment by kdsgambhir** [comment]
@cloudmode I tried to reproduce this error ``` Fails with error:2018/06/20 11:41:52 rpc error: code = Unknown desc = Error while unmarshalling: [Riley Street] as geojson: invalid character 'R' looking for beginning of value ``` .
This is because you have assigned predicate loc earlier a type geo(geolocation) and now you are assigning it a String value(name of a place).  You can delete that predicate from your schema and then run this ``` json:"loc,omitempty" ``` , this will work fine or simply you can over-write it in schema for delete edge using ```loc: string . ``` in schema. 
And the other solution is ``` Location string     json:"location,omitempty" ``` as told by you, by changing the name of predicate loc to location.

**Comment by cloudmode** [comment]
please note that I did a cut and paste from the document. I am aware of the possible fixes. The problem is the error is in the documentation.
