### ISSUE TITLE
Are you going to add Dgraph on Google Cloud Marketplace?

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph#2505]
Wondering if you guys are planning to add Dgraph on the [Google Cloud Marketplace](https://cloud.google.com/marketplace/)?

Would be great and useful for quick GKE Dgraph clusters - replicated or HA.

Thanks!

**Comment by danielmai** [comment]
This would be nice. We need to first figure out what we need to do to get on the marketplace.

**Comment by j143** [comment]
Although, configuring via a docker image is great but a simple to use deployment is quite handy. Please consider support for this. Thank you.

**Comment by johndouglascm** [comment]
Details are here: https://cloud-partners-program.appspot.com/registration/technology

**Comment by danielmai** [comment]
I registered at the above link and also added Dgraph to the marketplace idea forum: https://googlecloudplatform.uservoice.com/forums/599443-marketplace/suggestions/35524432-dgraph

**Comment by johndouglascm** [comment]
Happy to help out - likewise, AWS.  I believe they can be monetized.  It would be fun if you could spin-up a distributed instance in Seattle, Singapore and Dublin in a couple of clicks.

**Comment by danielmai** [comment]
Not sure what else needs to be done here besides wait for Google Cloud to respond to the idea forum.

**Comment by danielmai** [comment]
Is there anything to do besides wait for this?

On the topic of AWS, we're thinking that a CloudFormation template and an EC2 image that's set up to run Dgraph should work out nicely here for folks running on AWS. @johndouglascm, does that sound right or did you have something else in mind?

**Comment by insanitybit** [comment]
If there's interest, I have an aws-cdk file that allows one to set up a distributed (HA) version of DGraph using aws fargate. It does not autoscale, as a downside, but it means your hardware/OS is fully managed.

**Comment by good-idea** [comment]
@insanitybit I'm interested!

**Comment by insanitybit** [comment]
Cool, I just got it into master so it's easier to link now.

Here is the overall Fargate construct.
https://github.com/insanitybit/grapl/blob/master/grapl-cdk/index.ts#L933

There's two helper classes - one for Zero, one for Alpha.

Zero:
https://github.com/insanitybit/grapl/blob/master/grapl-cdk/index.ts#L755

Alpha:
https://github.com/insanitybit/grapl/blob/master/grapl-cdk/index.ts#L852

The goal here was to get managed OS/Hardware, but I needed service discovery. This means that every single instance of Zero or Alpha is its own Fargate service with a single task - tasks aren't addressable. Therefor you can't autoscale (because tasks autoscale, not services). Tasks aren't addressable with service discovery so that's just the way it is.

But if you're fine with not scaling as a tradeoff for getting managed OS/Hardware, this is probably a fine way to go.

**Comment by campoy** [comment]
Trying to use my contacts with Google to see if we can make this happen

https://twitter.com/francesc/status/1149823633839144960

**Comment by campoy** [comment]
Hey @danielmai 

Seems like we should follow the steps here:

https://cloud.google.com/marketplace/docs/partners/integrated-saas/

Including the Open Source Compliance checklist:

https://cloud.google.com/marketplace/docs/partners/open-source-compliance

**Comment by jdgamble555** [comment]
While it was added to the ideas form, it still needs to be added.  Perhaps someone who knows gcloud platform can do it: https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/submitting

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8428). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
