### ISSUE TITLE
weird variable assign

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#2566]
seems like when inside some block i assign one variable value to another one variable it just copies **all** it's values independently of block scope

```
POST localhost:8080/mutate

{
	set {
		_:node1 <common_pred> "" .
		_:node1 <custom_pred1> "" .

		_:node2 <common_pred> "" .
		_:node2 <custom_pred2> "" .
	}
}

POST localhost:8080/query

{
	all as var(func: has(common_pred)) { # 2 nodes here
		my as math(1)
	}
	
	filtered(func: uid(all)) @filter(has(custom_pred1)) { # 1 node here
		my1 as math(my)
	}

	result() {
		sum(val(my))
		sum(val(my1)) # 1 expected, got 2
	}
}

result:

{
    "data": {
        "filtered": [
            {
                "val(my1)": 1
            }
        ],
        "result": [
            {
                "sum(val(my))": 2
            },
            {
                "sum(val(my1))": 2
            }
        ]
    }
}
```

*actually, i was trying to achieve result as below, but this query doesn't work, so it would be very nice to have aggregates on vars in future release*

```
filtered(func: uid(all)) @filter(has(custom_pred1)) {
	sum(val(my))
}
```

**Comment by MichelDiz** [comment]
Aggregation is by design used in an empty-block. Can not be used at the level of a query.

Since I do not see the scope of the Issue according to the Issue title. Not a technical problem or a bug and is predicted. I think we should move this discussion to https://discuss.dgraph.io . It would be necessary to understand why this probable enhancement is necessary.

My comments on this:

There is nothing abnormal in the query presented. The mathematical function "my as math (1)" will be repeated according to the number of Nodes you have in the Var block. In the result() block it will return the sum of these Nodes found in the Var block. 

So, within the filtered() query. It will return 1 node only because there is only one node with predicate "custom_pred1" at this level (because it has a filter), if you remove the filter, you will get equal values. but separated by nodes.

The confusion is simple, you think when filtering on a block. In the other blocks the variables from previous blocks should suffer a side effect. Due to the use of the filter in the current block to the last one. But it turns out that the variable "my" is not stored in the block and will not be changed by its filters. Then the block with aggregation will access "my" via "my1" without undergoing filtering. It's true that By logic this should not occur. But that's not how it works.

In fact, that usage seems wrong to me. For me You have no reason to use a variable from another block in this situation. And want to filter to use in another block plus aggregation, that's a lot. Open a thread in the Discuss and we'll see if you really need it or let's find another wayout for your case.

Cheers.
