### ISSUE TITLE
Ratel without Cloudfront / Typeform

### ISSUE THREAD

**Issue by tr37ion** [dgraph-io/dgraph#2575]
Please remove external Cloudfront and Typefront scripts and move them to local.

**Comment by paulftw** [comment]
Thanks for your feedback.
We want to release new Ratel features much faster than we do with database server, so Cloudfront is a simple and reliable way of doing that (at least for now).

v1.0.9 will have give users an option to load Ratel from local as you've suggested, by appending `?cachedjs` to the Ratel URL. (In fact v1.0.8 already has that feature but due to my mistake has broken JS packaged in).

There's no clean way to move Typeform to local and keep it always up-to-date but we made sure that when Typeform fails to load Ratel remains fully functional. Let us know if it is actually causing problems for you.

Closing this issue for now as "working as expected". It will be fully fixed once new Dgraph release is cut.

**Comment by tr37ion** [comment]
In case of Typeform, you may consider using its open source alternative [Tellform](https://github.com/tellform/tellform) instead. From what I hear it is very similar to Typeform.

Using Ratel in an isolated network would be much appreciated.
