### ISSUE TITLE
Add man pages for linux clients

### ISSUE THREAD

**Issue by tr37ion** [dgraph-io/dgraph#2583]
Can you please add man pages for all applications (server, zero, ratel)?

**Comment by manishrjain** [comment]
Does running `dgraph alpha --help`, or `dgraph zero --help`, etc. not work for you? What more would be want in the man page?

**Comment by manishrjain** [comment]
I'm not clear if this is useful. Many users download Dgraph binaries, and a newer version might have a different set of options than previous one. Because the installation of Dgraph isn't standardized across operating systems, having man pages would only make things harder.

The right way to get the documentation is the `--help`. Man pages won't replace that.
