### ISSUE TITLE
Improve error messages to point at specific line and character number

### ISSUE THREAD

**Issue by samhain1138** [dgraph-io/dgraph#2609]
## Experience Report

I am experienced with graph databases but new to dgraph.
I'm afraid to report the error messages and documentation are in extremely poor state.

I was trying to run a mutation setting some data, similar to the one in the quick start guide.
The error I received was:
`{"errors":[{"code":"ErrorInvalidRequest","message":"Invalid mutation formatting."}]}`
This does not help me understand the issue or debug it in any way shape or form.
This is a multi-line set mutation, so at the very least, the parser could tell me what line the error is at, not to mention the actual character, at which position, and what it expected to find.
After some trial and error I figured out it was the "#" comment syntax which I swear another issue/PR said is "supported".

### What you wanted to do
I wanted to set some data. In the event of me screwing up with formatting, I'd expect to know exactly why, at which line number and what column.
Additionally "#" comments should work within mutation or any query for that matter.

### What you actually did
Opened an issue on GitHub because this is unacceptable behavior from a query parser for a database.

### Why that wasn't great, with examples
Since if I could have the line number and column number, I might have been able to set data for the first time in dgraph.
However, my absolute first experience with dgraph tells me it's nowhere near "production-ready" if it can't even report issues originating from the query parser -- I wouldn't want to imagine debugging the engine or dealing with disaster recovery.

**Comment by MichelDiz** [comment]
Hi samhain1138, 

Thank you for your experience report.

The error
`{"errors":[{"code":"ErrorInvalidRequest","message":"Invalid mutation formatting."}]}`
always will mean that you had a typo mistake. And only that. 

Depending on the client you are using you may are confused. Please inform the client you are using (Ratel? Dgraph-js? So on). Using Ratel there is a specific syntax for running mutations and queries. The clients do not require a specific syntax for operations. For they are operations in themselves, in the client.

If you have difficulties with RDF formatting, I recommend using operations in JSON.
https://docs.dgraph.io/mutations/#json-mutation-format

Also do our Tour http://tour.dgraph.io

If you are using a specific client, its documentation or basic usage should be easily found in it's repository or an appropriate place (like godoc.org/ documentation for Go Client).

**About the Comments**, you can use comment in queries and RDF mutations. Only JSON format you can not use comments.

Here is a valid example of an RDF with comments on different points of the mutation.
```
{
  set {
    # comment here
    <0x01> <name> "Alice" .  # comment here
    # comment here
  }
}
```

> Since if I could have the line number and column number, I might have been able to set data for the first time in dgraph.

### IMHO

I get it, but this statement does not seem to corroborate with the premise that the Dgraph is not production-ready. This is a tool (Ratel?) evaluation that you have not yet mastered. At the moment you understand the syntax of queries and mutations. You will know quickly how to resolve typo mistakes.

#### So why it's not "production-ready" related?

For example, no one was born knowing how to use any SQL client. You need to understand all syntax and operations. SQL has more than 44 years of market experience and Dgraph has appeared 2 years ago. noSQL is more or less two decades old and only now in the last 5 years have the developers invested in it.

You need to give more time experience with Dgraph. I initially did not have much difficulty since I already used GraphQL. It was easy for me to understand Dgraph as a whole. But I understand anyone who has no experience with graphQL may have some difficulty with Dgraph. But it is momentary.

This statement is like the critics of Linux. Many people do not go to linux because they find Windows easier and more comfortable. Criticize the supposed complexities of Linux. But they forget that they were born in a world where Windows dominates most machines called PCs. They did not get(or gived) a chance to meet a Distro and realize that it's not that complicated. It's just annoying sometimes. Just like windows, but not worse xD

But you understand? how to criticize an electric car if we have more than a century of immersion with combustion cars? it is unfair to require that two different things be equal without a personal sacrifice.

#### Finally.

Dgraph is a DB graph, but its proposal is based on GraphQL (which is graph based) and it delivers that proposal accurately. And for me the format that Dgraph follows is much more efficient and with logic for Graph DBs. The others try to make more comfortable those coming from SQL DBs. This is not a Dgraph proposal. It differs from others graph database, so anyway if you have any graph DB experience. it requires new dedication. Or GraphQL experience.

### AND OF IMHO

But in fact you're right about the Dgraph returning at which position is the typo error. This can be evaluated later, it is not something crucial that disrupts the effective use of the Dgraph. But it's important.

Please open a new issue requiring this enhancement and refer to this issue. I will close it because it is report Experience already analyzed by me. Thanks again for the feedback. I hope I covered everything. Any doubt I am available

Cheers.

**Comment by MichelDiz** [comment]
Reopened because I noticed that the title "Experience Report" is not related to just experience xD sorry. So the focus of this issue is its title "Improve error messages to point at specific line and character number"

**Comment by srfrog** [comment]
This feature is now in master branch. Closing this.
