### ISSUE TITLE
Tutorial to explain how to launch the project in debug mode

### ISSUE THREAD

**Issue by GaetanLhoest** [dgraph-io/dgraph#2704]
At the moment, the project is not easily launchable in debug mode.
Indeed, with the last version of delve and Go, there is the error message:

```
decoding dwarf section info at offset 0x0: too short
```

I suppose the dev team managed to launch the project in debug mode, otherwise, it would be a nightmare to develop and maintain. 

Could you describe how you are proceeding? It would be useful to dev like me, trying to develop new functions in Dgraph, such as other geographic functions and a GIS plugin.

**Comment by gitlw** [comment]
Hi @GaetanLhoest , 
I tried debugging using the delve debugger, and ran into the error
could not launch process: could not get .debug_frame section: could not find .debug_frame section
According to https://github.com/golang/go/issues/23733, it turns out that the golang 1.10 I'm using does not work well with debuggers. 

Then I switched to golang 1.9 and then delve starts working, and I can debug dgraph in any directory, e.g. to debug dgraph zero, you can use the command
dlv debug github.com/dgraph-io/dgraph/dgraph -- zero

The delve debugger docs has more instructions on how to use it https://github.com/derekparker/delve
Also I tested setting my go sdk to golang 1.9 inside GoLand, and debugging also worked.

Finally, I'd like to suggest not to rely too heavily on the debugger since generally speaking, debuggers will "pause the world" after hitting a breakpoint, and thus may change the behavior of a concurrent program, e.g. causing network timeouts etc. That's why many tricky concurrency issues won't show up when you attach a debugger to it. In this regard, it's better to rely on logs to analyze a program's behavior.

Hope that helps.

**Comment by gitlw** [comment]
BTW, I'm closing the issue now. Feel free to reopen/comment if you still have any questions. Thanks for using dgraph.
