### ISSUE TITLE
The test TestSystem/delete_all_reverse_index is flaky

### ISSUE THREAD

**Issue by gitlw** [dgraph-io/dgraph#2717]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.10-rc1-25-g3897db23

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
8G, Fedora

- Steps to reproduce the issue (command/config used to run Dgraph).
1. Start the dgraph cluster by running `run.sh` inside $GOPATH/src/github.com/dgraph-io/dgraph/dgraph
2. Run the test multiple times with the following script and eventually the test could fail. If you don't see the failure, try to increment the number of runs and try it again.

> #!/usr/bin/env bash
> for i in $(seq 1 10); do
>    go test -v -run=TestSystem/delete_all
> done

- Expected behaviour and actual result.
The test should always succeed.

**Comment by manishrjain** [comment]
Is being caused due to not doing a read-modify-write cycle. Our mutation path does NOT check if the server has seen all previous commits for performance reasons. Only the query path does. So, if a txn does not query for anything (like in the live loader), then all mutations would be allowed to run concurrently, instead of blocking on each other. Typically this is good for performance and OK for correctness, because the live loader does not delete anything.

This test is actually deleting blindly after doing a write in a previous txn. Sometimes, the Alpha doesn't get to apply the commit before the blind delete is proposed. Hence, we have this race condition, causing this test failure. A working solution here would be to do a read before doing a write.
