### ISSUE TITLE
Run ineffassign on Dgraph

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#2860]
Run and fix the violations found by ineffassign:

https://github.com/gordonklaus/ineffassign

**Comment by martinmr** [comment]
I can take this over since I am already doing it for badger.

**Comment by srfrog** [comment]
sure, let me push my branch.

**Comment by martinmr** [comment]
Thanks.

**Comment by martinmr** [comment]
Most issues are fixed. Most errors remaining are complaining about 

I need to fix the error string. Lucas pointed out that they should start with lowercase and it turned out golint was not showing those warning because they didn't have enough confidence. This is not as important so I'll fix them later once I find an automatic way to do it.
