### ISSUE TITLE
Add access control mechanism to Zero

### ISSUE THREAD

**Issue by srfrog** [dgraph-io/dgraph#2930]
> There's no authentication, right? So even if the dgraph server was started by root, it can still be shut down by any user?

That's correct. We need to add some access control to Zero.

_Originally posted by @srfrog in https://github.com/dgraph-io/dgraph/pull/2928#issuecomment-457029300_

**Comment by Graphpinto** [comment]
Couple of options here - 
1. Create a super user stored in config (with password hashed) during installation, and make the end point only callable by the super user
2. Make the endpoint invokable only from local host and not from remote host

**Comment by codexnull** [comment]
My thinking was to use TLS (aka SSL). Just require /admin requests to be done using a secure connection and that can only be established by presenting the right certificate. I was thinking most of the hard work in that case could be pushed down to the TLS/crypto libraries rather than dgraph itself.

Disclaimer: I have not actually looked into how feasible this would be.

**Comment by srfrog** [comment]
Technically that is already done in the `dgraph cert` command. Just need to make a cert for zero but it hasn't been tested.
