### ISSUE TITLE
Review link in documentation.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#2993]
https://github.com/dgraph-io/dgraph/blame/release/v1.0.11/wiki/content/design-concepts/index.md#L194

This line in design-concepts points to an internal link that does not exist (deploy#data-sharding). The purpose seems to be to indicate an explanation of data-sharding.

The ideal link would be https://docs.dgraph.io/deploy#understanding-dgraph-cluster

But as I am in doubt, I decided to open this issue. For the word used in the Link ("groups") seems to have another connotation. This needs to be revised. We need to understand the intent of this sentence and the link. To address the correct link.

**Comment by danielmai** [comment]
As with the majority of the design concepts page, the Group section in question is under the existing warning:
> "Outdated: Sections below this one are outdated. You will find [Tour of Dgraph](https://tour.dgraph.io/) a much helpful resource."

---

I don't think a link for "groups" is necessary. After all, this section is titled "Group" and should already define what a group is in here. The link refers to [this old version of the docs](https://docs.dgraph.io/v0.8.3/deploy/). We can remove this link for now. In fact, we should redo this Group section entirely since it's inaccurate.

Some inaccuracies:

* > A set of Posting Lists sharing the same Predicate constitute a group. Each server can serve multiple distinct groups.

    Although this is true by this definition, it's now confusing since our current usage of "group" in Dgraph refers to groups of Alphas in the cluster, not groups of predicates.
* This section suggests that a single predicate can be further sharded into multiple groups, which isn't the case. 
* It also mentions a group config file that determines which servers serve a particular group and that—**in future versions**—Alphas can move tablets based on heuristics. We're already in that future, and there's no group config file per-se but is shown in /state.

**Comment by danielmai** [comment]
Removed the link and rewrote the entire section. The change is now live in the master and v1.0.11 docs.
