### ISSUE TITLE
GraphQL+- doesn't seem to support recursion/infinite chains

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3030]
If I have a node which connects to another node which connects to another node ....

I don't seem to be able to perform a query that fetches the entire chain from a starting node all the way down. In this scenario, the pagination-based keywords doesn't seem to work in terms of "depth" either.

Is this a GraphQL+- limitation?

The intended use-case here is something akin to a dependency chain (i.e. each node may be dependent on multiple nodes, AND there may be circular references too).

**Comment by pjebs** [comment]
This may be useful: https://github.com/stems/graphql-depth-limit

**Comment by MichelDiz** [comment]
Have you tried Recurse Query? https://docs.dgraph.io/query-language/#recurse-query

Dgraph has few logical limitations by default to avoid congestion. You can change the limitations by placing values ​​manually.

It's good that you always put constraints on users so that they are not able to create chaos in your cluster. And almost never will a user need a giant query. I can not even imagine a product that needs an almost infinite data. How it could be shown or how to deal. Paging could do this job.

But I do not think There is a limitation for this in Dgraph.

Cheers.

**Comment by pjebs** [comment]
Well the use case is a dependency package manager. I have to get all nodes. In that circumstance.

**Comment by MichelDiz** [comment]
Nice, you can do it with Recurse Query. But you have to define the depth. 
Also you can have a mix of Paging and Recurse. So you do Paging (using Var block) 
in "root nodes" and expands its deep relations with Recurse query.

Also you can have expand all if you don't wanna type the predicates one by one e.g:
```
	{
		me(func: uid(0x1)) @recurse {
			uid
			expand(_all_) {
			    uid
			    expand(_all_) {
			         uid
			         expand(_all_) 
			    }
		      }
		}
	}
```

If you find a limitation that you can't overcome, open an issue with details of your experience. 
Explaning what wasn't great, with examples as the Experience Report asks to do.

Cheers.
