### ISSUE TITLE
dgraph continues answering OK after OOM

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3038]
dgraph version: 1.0.10

we had OOM during data load on dgraph alpha node. after that node disappeared from logs, so it's not fetching data for replication. but it still answers 'OK' on health check (8080/health), so it's not restarted automatically because we can't determine that there is something wrong with this node.

need to adapt health check to check threads related to data load (badger or whatever else)

**Comment by makitka2007** [comment]
logs related to OOM: https://drive.google.com/file/d/1d5yxWxSUKUoMYTvlyEqaPk2IpwKFLWFt/view?usp=sharing

**Comment by srfrog** [comment]
It's not possible to catch OOM in Go, they just get converted to panics. And Dgraph is designed to bounce back if there's a failure. But in the case o f an OOM condition the right thing to do would be to shutdown the node. Would need to recover the panic and inspect the error, in this case `out of memory`, but not all failures deserve a shutdown.

Related to #2646

**Comment by srfrog** [comment]
Also keep in mind that during bulk loading, the memory usage will be higher than expected. See https://docs.dgraph.io/deploy#running-oom-out-of-memory

**Comment by makitka2007** [comment]
yep, but it didn't happen during bulk load, just on replication from other node (i think)
despite node was not fetching data from leader it still answered "OK" on /health, so it was impossible to detect a problem there and perform shutdown and restart

maybe i understand the problem wrong, but it seems to me that not all threads are sending heartbeat or checked somehow else by health check. so, if replication thread fails, node is till working and answering OK.

i am assuming that from logs. because according to logs there was not restart of that node. if you say that any OOM in any thread in go causes panic that means that the whole node goes down, then maybe there is some issue with our logs, and node was actually restarted

**Comment by srfrog** [comment]
I think you are correct to think this is an issue, if we detect OOM I think the node should shutdown. The problem is that right now we don't have that ability. The Go runtime will run down the stack and check if the panic (OOM) can be recovered. This is a bit different to running a C++ program, for example, which would just crash. The server ports run in their own go routines and are controlled by the same shutdown flag, we need to make sure that flag is set when OOM is detected, which clearly is not happening now.

**Comment by manishrjain** [comment]
In most cases, I've seen the OS would kill the process if the process is going above their memory limits. That's a clear kill signal. In this case, this looks like an OOM panic when Dgraph tries to allocate memory in some place. There are memory allocations all over the codebase (any object on heap is a malloc), so it's hard for the DB to catch and recover this OOM panic.

FWIW, I tried to create a code-snippet to see if we can recover from this panic, but I couldn't: https://play.golang.org/p/zVdi10RDjkt

Not that we can implement a graceful recovery from OOM panic, but see if we can catch this panic and at least kill the Dgraph process.

**Comment by jarifibrahim** [comment]
>FWIW, I tried to create a code-snippet to see if we can recover from this panic, but I couldn't: https://play.golang.org/p/zVdi10RDjkt

The OOM failure isn't a `Panic()` call, it's a `Fatal()` call (see https://github.com/golang/go/blob/master/src/runtime/panic.go#L617)

We can recover from `Panic()` but not from `Fatal()` call (fatal = panic + os.exit).

So the question is was it really a OOM failure? Because if it was, the main process should've crashed.
Also, I can't find any errors in the logs provided. I think we log all errors, don't we?
