### ISSUE TITLE
Deploy on OpenShift

### ISSUE THREAD

**Issue by lobosan** [dgraph-io/dgraph#3127]
Hi, I just found this project and it would be great if you could create a series on Udemy showcasing how to deploy a production ready cluster on OpenShift and cover topics related to:

- How to move from traditional enterprise databases such as SQL Server and Oracle to Dgraph
- Monitoring
- Migrations
- Transactions/Rollbacks
- Administration
- And everything else in your docs

All the best

**Comment by danielmai** [comment]
Thanks for sharing your video suggestions @lobosan. We definitely want to have more videos about Dgraph. We've released a few new videos already and plan to release more.

I'll close this issue since this isn't a technical bug or feature request about Dgraph. If you have further suggestions you can reach out to us over at https://discuss.dgraph.io.
