### ISSUE TITLE
Shuffler phase may end up creating too many go routines

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/dgraph#3297]
The issue was first reported by @codelipenghui. The reporter raised a PR to fix the issue https://github.com/dgraph-io/dgraph/pull/3276. Later, @codexnull pointed out that the PR actually broke the bulk loader and raised a PR to revert the changes https://github.com/dgraph-io/dgraph/pull/3288.

**Comment by campoy** [comment]
If I understand correctly this is not currently an issue as the code was reverted?

If so, please update the title to indicate what this issue is about.

**Comment by mangalaman93** [comment]
@campoy the issue still exists but only relevant for very large amount of data. The proposed fix solved the issue but created another issue. It was reverted for the same reason. This solution will require more thought and work than currently necessary given that we do not often see this issue.

**Comment by martinmr** [comment]
I don't think this issue is relevant anymore. Manish refactored the bulk loader a while ago and the shuffler phase does not exist anymore in the current version of the bulk loader.

I tried to find similar code in the current master but I couldn't. @manishrjain can you confirm whether this issue is still relevant?

**Comment by manishrjain** [comment]
Does not seem relevant anymore. I removed the shuffler phase.
