### ISSUE TITLE
[feature] Avoid high latency while index update

### ISSUE THREAD

**Issue by codelipenghui** [dgraph-io/dgraph#3320]
### What you wanted to do

I want to use dgraph to support online business scenarios, but If the index is not defined in advance and do index update after application is an online service, this will make the request very slow.

So, is it possible to provide a mechanism to avoid high latency of request while index update.

**Comment by martinmr** [comment]
I am a bit unclear on what you mean. Do you mean developing a service using Dgraph and updating the schema to generate indices AFTER your service is in production?

If that's the case, other transactions will have to slow down while the index is being rebuilt as doing otherwise would break consistency.

Two things to consider.

1. Do not perform schema changes while in production or wait for a time with low traffic to perform these type of changes. Ideally, you know which kind of queries you need to run before getting on production and can select queries accordingly.

2. Maybe best-effort queries could help in these situations. You sacrifice correctness for speed but that might be an acceptable compromise. This only works for queries, not mutations though.

**Comment by MichelDiz** [comment]
Closing this, due inactivity. Feel free to reopen if necessary.
