### ISSUE TITLE
test.sh script should run more tests by default

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#3372]
Right now, there are a lot of tests that need a custom cluster but should still be run by default every time a PR is opened (they either don't take a long time or are important). Having them be disable by default is not great.

There should be another way of specifying which tests not to run by default than needing a custom cluster.

**Comment by codexnull** [comment]
The reasons custom cluster tests are not run by default are because they are easy to identify programmatically and bringing clusters up and down can take a significant amount of time, so eliminating those were an easy way to reduce the default test run time.

If we want to change which tests are run we should probably discuss how to select the tests. Naming convention? Test list files? Build tags? There are lots of ways it could be done.

Depending on what we decide it may also be a time to replace test.sh with something that's not a shell script, like a python script.

**Comment by martinmr** [comment]
Closing this issue as this was fixed by using the -c flag.
