### ISSUE TITLE
Filter on recurse query not working

### ISSUE THREAD

**Issue by zerbitx** [dgraph-io/dgraph#3388]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.14

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
MacOS Mojave
2.9 Ghz Intel Core i9
32 GB Ram

- Steps to reproduce the issue (command/config used to run Dgraph).

Use the attached json file to add all randomized contact information (sorry about the names, they were randomly generated)

[random_testdata.json.zip](https://github.com/dgraph-io/dgraph/files/3159634/random_testdata.json.zip)

Run the schema change

`contact: [string] @index(term, fulltext, trigram) .`

Then run the query
```
{
  EC as var(func: has(issue-example)) @filter(anyofterms(contact, "emergency-contact"))
  H as var(func: has(issue-example)) @filter(anyofterms(contact, "home"))
    
  test(func: has(issue-example)) @filter(NOT uid(EC, H)) @recurse  {
    phone
    contact @filter(NOT uid(EC, H)) {
      phone
    }
  }
}
```

- Expected behaviour and actual result.

Expected not to see any results with either "emergency-contact" or "home" in the contact list

**Comment by danielmai** [comment]
Hi @zerbitx, thanks for sharing an example data set and query for this issue report.

There are some things you can do to get the expected results with a `@recurse` query.

1. In a recurse query, all predicates must be specified as a single level after the root func.
2. Your schema describes `contact` as a string and `phone` as a uid edge to other nodes. So your filter to filter out UIDs should be for the `phone` predicate since that's the uid edge.

```
{
  EC as var(func: has(issue-example)) @filter(anyofterms(contact, "emergency-contact"))
  H as var(func: has(issue-example)) @filter(anyofterms(contact, "home"))
    
  test(func: has(issue-example)) @filter(NOT uid(EC, H)) @recurse  {
    phone @filter(NOT uid(EC, H))
    contact
  }
}
```

What happened in the original query is this: You've correctly found the set of nodes to filter out in the first two query blocks. But in the case of a "phone -> phone -> contact" relationship, the root func filter only filtered out the initial set of nodes of `phone` edges, not any deeper traversals for `phone`.
