### ISSUE TITLE
Expanding a predicate when a filter returns no nodes results in an unclear error message

### ISSUE THREAD

**Issue by Kingloko** [dgraph-io/dgraph#3512]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

1.0.14
- Have you tried reproducing the issue with latest release?
no

- What is the hardware spec (RAM, OS)?
Ubuntu, 32GB

- Steps to reproduce the issue (command/config used to run Dgraph).
run a query of this form where the base query should return no nodes
```
{ 
  q(func: eq(id, can_never_happen)){
    ~src{ 
        expand(_all_)
      }
  }
} 
```

- Expected behaviour and actual result.

expecting: Empty list, indicating there were no matches for my query 
actual: `Unhandled pb.node expand with parent ~src"`

**Comment by MichelDiz** [comment]
This seems to be related to https://github.com/dgraph-io/dgraph/issues/3198

Other ways to get this error

```
{ 
  q(func: has(src)){
  ~src{ expand(_all_) }
}
}
```
`": Unhandled pb.node expand with parent ~src"`

### BTW
If I use a existing edge in the schema, it will return
`": Predicate src doesn't have reverse edge"` This error is acceptable when you have the predicate indicated in the schema.
But the right error for otherwise should be `": Predicate src doesn't exists"` from the above query and below as I'm doing this test in a Dgraph instance that don't has "src" pred in the schema. Dgraph shouldn't throw any other error in this specific case. This can confuse the user.

BTW² Kingloko is doing his test in a Dgraph instance that has "src".

```
{
  q(func: has(genre)){
  ~src { expand(_all_) }
}
}
#": Predicate src doesn't have reverse edge"
```

>`dgraph.user.group` has reverse indice
```
{ 
  q(func: has(~dgraph.user.group)){
  ~dgraph.user.group { expand(_all_) }
}
}
```
`": Unhandled pb.node expand with parent ~src"`


For some reason this works as expected:

```
{
  q2(func: has(rating)){
  ~rating (first: 10){ expand(_all_) }
}
}
```

Coming from valueVarAggregation func:
https://github.com/dgraph-io/dgraph/blob/f97d6b57c46fa6897e1a2f121add48a12d42a93d/query/query.go#L1371

**Comment by MichelDiz** [comment]
## UPDATE

Testing this on master I wasn't able to reproduce this I think @martinmr fixed it.

```
src: [uid] @reverse .
id: String @index(exact) .
name: String .

 type Generic {
   name: string
   id: string
   src: [id]
 }

```

```
{
  set {
    _:m <id> "can_never_happen" .
    _:m <dgraph.type> "Generic" .
    _:msrc <src> _:m .
    _:msrc <name> "test" .
    _:msrc <dgraph.type> "Generic" .
  }
}

```

```
{ 
  q(func: eq(id, "can_never_happen")){
    uid
    ~src { 
       uid
        expand(_all_)
      }
  }
} 
```

### Result

```
{
  "data": {
    "q": [
      {
        "uid": "0x31",
        "~src": [
          {
            "name": "test"
          }
        ]
      }
    ]
  }
```
