### ISSUE TITLE
Provide better error messages on error in `@if` blocks and only allow `len` function

### ISSUE THREAD

**Issue by animesh2049** [dgraph-io/dgraph#3963]
query having `eq` function in condition, gives weird error message. 
Example query:
```
upsert {
  query {
    me(func: eq(name, "Animesh")) {
      u as uid
      n as name
    }
  }

  mutation @if(eq(n, "Animesh")) {
    set {
      uid(u) <name> "Ashish" .
    }
  }
}
```

Example error:
```
details = "while parsing query: "{\n          me(func: eq(name, \"Animesh\")) {\n            u as uid\n            n as name\n          }\n        __dgraph5979021689109993804__ as var(func: uid(0)) @filter(eq(n, \"Animesh\"))}": Some variables are defined but not used
Defined:[__dgraph5979021689109993804__ n u]
Used:[__dgraph5979021689109993804__ u]

```

**Comment by dai-dao** [comment]
Hello, it's my first attempt to contribute to this repo. I wrote a test in upsert_test and it seems that 
 the ParseMutation function doesn't really check for this error anymore, but Parse function for normal query does. So I can't re-produce this error with any upsert / mutation.

Does this mean issue closed? 

Cheers

**Comment by MichelDiz** [comment]
Updated error today in v20.xx.x
```
{
  "name": "t",
  "url": "http://localhost:8080/mutate?commitNow=true",
  "errors": [
    {
      "message": "Some variables are defined but not used\nDefined:[__dgraph__0 n u]\nUsed:[__dgraph__0 u]\n",
      "extensions": {
        "code": "ErrorInvalidRequest"
      }
    }
  ]
}
```

**Comment by MichelDiz** [comment]
Thanks, @animesh2049 for the issue, I think Aman had changed the title for some reason and it wasn't what you wanted to ask in the original title. I think your original issue wanted the same goal as #5281 so I gonna close this in favor of #5281. As it is more precise and it is already being worked by the user who asked the support.
 
About the error message part. I noticed that the response format has changed a lot since your post/issue was created and I had opened a more precise one on that topic. The #5303 with other goal.

@dai-dao please, test your test approach against Master and see if you have the same issue you had mentioned in your comment. If so, please comment in #5281 or #5303 if it is related to one of them.

Cheers.
