### ISSUE TITLE
Behavior of cascade not clear with aggregation

### ISSUE THREAD

**Issue by animesh2049** [dgraph-io/dgraph#4024]
### What version of Dgraph are you using?
version: 5b20d411f7cb21fe575503e70f60ca48bb794bb1

### Steps to reproduce the issue and expected behaviour and actual result.

Behavior of aggregators is not clear when used with `@cascade`.
Data:
```
_:animesh <name> "Animesh" .
_:ashish <name> "Ashish" .
_:aman <name> "Aman" .
_:prashant <name> "Prashant" .

_:animesh <age> "24" .
_:ashish <age> "27" .
_:aman <age> "26" .

_:animesh <friend> _:ashish .
_:ashish <friend> _:aman .
_:aman <friend> _:prashant .
```
query:
```
{
  var(func: has(name)) @cascade {
    friend {
      age_var as age
      friend {
        age
      }
    }
  }
  me() {
    min(val(age_var))
  }
}
```
Response:
```
{
  "data": {
    "me": [
      {
        "min(val(age))": 26
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 28933,
      "processing_ns": 7890307,
      "encoding_ns": 5757,
      "assign_timestamp_ns": 652749
    },
    "txn": {
      "start_ts": 154
    }
  }
}
```
`age_var` should only contain those nodes, whose `friend's` have age and `friend's friend` have `age`. Here root query will have uids of `animesh, ashish, aman, prashant`, 
```
animesh --(friend)----> ashish (name: "Ashish", age(aliased as age): 27) --(friend)--> aman (name: "Aman", age: 26)
ashish --(friend)--> aman (name: "Aman", age(aliased as age): 26) --(friend)--> prashant(name: "Prashant") # Prashant doesn't have age so this should be filtered out due to cascade
aman --(friend)--> prashant(name: "Prashant") # This should also be filtered 
prashant # This should also be filtered
```
So `age_var` should only have uid of `ashish` and `min(val(age))` should be 27, but we are getting 26 which is `aman's age`.
Right now it seems `@cascade` is being ignored.

**Comment by insanitybit** [comment]
I'd like to suggest this as a feature. This greatly complicates queries for me, and is really unintuitive. I've had a long standing bug in my project because of my assumption that cascade was impacting the results of var queries.


Here is one example I have for my own project.

This is the 'correct' (no-cascade version)
https://gist.github.com/insanitybit/f3b51d477fbb69c3fecb4263e1a235ca

It has to be rewritten as such:
https://gist.github.com/insanitybit/a0151c4afd03a981b715296d689e42a9

Notably, I've had to introduce:
* A binding for every edge in the var query, which is quite painful
* An extra filter on the `result` query

This becomes much more complex as you add multiple var blocks. A new binding for every edge, for every var block, and a filter for every group of var block bindings. As I'm generating my queries from code this increase complexity quite a bit for me.

It's also unintuitive that cascade would behave differently at all in a var block vs a query block, and that it is effectively silently dropped today is even less of an expected behavior.

**Comment by MiLeung** [comment]
I still have this issue. The way I work around it is I have to do something like this

```
settings {
  notifications @filter(eq(whenSomeonePosts, true)) {
    # traversing back and forth cuz cascading here doesn't filter UIDs here
    ~notifications {
      ~settings {
        peers as uid
      }
    }
  }
}
```
but the issue is you have to add more `@reverse`s to your schema in order to make it work.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8449). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
