### ISSUE TITLE
alpha process crashed after run some query

### ISSUE THREAD

**Issue by aliakbari** [dgraph-io/dgraph#4094]
### What version of Dgraph are you using?
1.1.0
### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
2G, Windows

### Steps to reproduce the issue (command/config used to run Dgraph).
.\dgraph alpha --lru_mb 2048 --zero localhost:5080

### Expected behaviour and actual result.
![dgraph](https://user-images.githubusercontent.com/3436602/65810726-f6113400-e1ba-11e9-812b-5d43cfcdffb0.png)

**Comment by MichelDiz** [comment]
Duplicated of https://github.com/dgraph-io/dgraph/issues/3800
The solution is already merged https://github.com/dgraph-io/dgraph/pull/4007
This will be in the next RC release, but you can build master to test it before release. But keep in mind that building from master isn't recommended. Due to possible errors or approaches not documented yet.

Feel free to reopen if it continues when an RC release comes.

**Comment by aliakbari** [comment]
Are versions not stable? I just started and it's really bad to eat this bug at the beginning

**Comment by aliakbari** [comment]
Is this problem only in windows? Transfer to Linux?

**Comment by MichelDiz** [comment]
Yes, it is only in Windows. Linux is the main target of Dgraph's release support. It also runs in any OS via containers (Docker, K8s).
