### ISSUE TITLE
Make testutil functions that return a client also return an error.

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#4172]
Right now, the function is panicking and causing the test binary to end. The error should be passed to the caller and the caller should decide what to do (ideally skipping tests instead of crashing).

**Comment by shekarm** [comment]
Please update the JIRA issue and based on the priority, we can "schedule" the work.

—
Shekar Mantha

Sent from Front

--- original message ---
On October 15, 2019, 3:12 PM EDT notifications@github.com wrote:


Right now, the function is panicking and causing the test binary to end. The error should be passed to the caller and the caller should decide what to do (ideally skipping tests instead of crashing).

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by martinmr** [comment]
https://github.com/dgraph-io/dgraph/pull/4176
