### ISSUE TITLE
Predicate named "code" or "message" generates errors

### ISSUE THREAD

**Issue by miko** [dgraph-io/dgraph#4361]
### What version of Dgraph are you using?
master
### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
not relevant

### Steps to reproduce the issue (command/config used to run Dgraph).
Using dgraph:master and ratel ?dev:

1. mutate:
```
{
 set {
    _:x <name> "Bob" .
    _:x <code> "BobCode" .
    _:x <dgraph.type> "MyType" .
 }
}
```
2. create type MyType with both predicates
3. query:
```
{ res(func: type(MyType)) {
expand(_all_)
}}
```
4. query:
```
{ res(func: type(MyType)) {
code: code
name: name
}}
```
Step 4 generates error:
`Message: query alias [code] not allowed`

Moreover, you cannot edit schema using ratel (Schema->Types->MyType->Change Type generates blank page).

### Expected behaviour and actual result.
Both steps 3 and 4 should return the same result

I have found the comment in the source here: https://github.com/dgraph-io/dgraph/blob/master/edgraph/server.go#L1072 stating that "code", "message" and "uids" is used by the HTTP API.
But the problem for me is that some predicate names are disallowed (when using aliases) for no reason - is that documented anywhere?
Would it be possible if HTTP API used more private "_code" and "_message" names, as those are pretty standard as predicate names?  Or maybe the HTTP API implementation could be improved so that condition wouldn't be needed?

**Comment by campoy** [comment]
Wow, good catch and great report @miko !

Indeed, this seems like a potential release blocker for v1.1.1. (cc @shekarm )

# Context

The cause of this issue is the fact that we started returning the result of queries in upserts.
This was necessary for GraphQL support and was seen as a useful change for many other users.

Let's look at the response change for this upsert block:

```graphql
upsert {
  query {
    names as q(func: has(name)) {
       name
    }
  }
  mutation {
    set {
      uid(names) <name> "a" .
    }
  }
}
```

While in v1.1.0 you could run this query and obtain the result below (notice there are only three fields in "data")

```json
{
  "data": {
    "code": "Success",
    "message": "Done",
    "uids": {
      "uid(names)": "0x1"
    }
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 49600,
      "processing_ns": 53113700
    },
    "txn": {
      "start_ts": 2,
      "commit_ts": 3,
      "preds": [
        "1-name"
      ]
    }
  }
}
```

Now (with v1.1.1) we return the result of the query block named `q` in the upsert response:

```json
{
  "data": {
    "q": [],
    "code": "Success",
    "message": "Done",
    "uids": {
      "uid(names)": "0x1"
    }
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 77200,
      "processing_ns": 995401700,
      "encoding_ns": 10200,
      "assign_timestamp_ns": 16670800,
      "total_ns": 1013476500
    },
    "txn": {
      "start_ts": 1,
      "commit_ts": 3,
      "preds": [
        "1-name"
      ]
    }
  }
}
```

Notice the `"q": []` inside of `"data"`. The decision of making the response appear at this level means we can have collisions in between query block names and the fields `message`, `code`, and `uids`.
This is why those were disallowed in queries.

# The bigger issue

A bigger issue is the fact that these were disallowed in a much more aggressive way than needed.
This change, instead of only affecting query block names inside of upserts, affects all identifiers (query block names, and aliases) inside of all queries. This is clearly a big breaking change that should not be released.

# Proposed fix

Instead of disallowing these query block names (which would be a backward breaking change) I propose moving these results into a `queries` subfield. This is OK, since these results were not returned previously, so moving them won't break anyone's code.

The result should then be:

```json
{
  "data": {
    "queries": {
      "q": []
    },
    "code": "Success",
    "message": "Done",
    "uids": {
      "uid(names)": "0x1"
    }
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 77200,
      "processing_ns": 995401700,
      "encoding_ns": 10200,
      "assign_timestamp_ns": 16670800,
      "total_ns": 1013476500
    },
    "txn": {
      "start_ts": 1,
      "commit_ts": 3,
      "preds": [
        "1-name"
      ]
    }
  }
}
```

**Comment by manishrjain** [comment]
Agree with the analysis and proposed solution.
