### ISSUE TITLE
Can you guys give us a complete config file 

### ISSUE THREAD

**Issue by wuqifei** [dgraph-io/dgraph#4445]
## Documentation

I like dgraph, and use its demo, it is really good. 
I want to have a complete config file and complete config file description.

I used to use kafka, so can you guys give us a config file like kafka.

**Comment by martinmr** [comment]
Dgraph does not have configuration files. You configure it using the flags for the `dgraph alpha` and `dgraph zero` files. You can use the '--help' flag to 

However, if you are using a tool like docker, you can have configuration files to describe all the containers in your cluster. We use docker-compose for this. Look for all the files called `docker-compose.yml` in this repo for examples. There is also a tool in the `compose` directory that we use to create these configuration files when writing tests. I'd recommend taking a look at it and see if you could adapt it to your use case.

**Comment by martinmr** [comment]
EDIT: the framework that we use for processing flags actually supports a config file (via the `--config` flag). However, these file just overwrites the default values for the flags and flags specified directly on the command line have preference over the values from the file. Our preferred method is still specifying the flags directly since it's a bit more explicit.
