### ISSUE TITLE
LDBC_SNB benchmark for Dgraph

### ISSUE THREAD

**Issue by ouzensang** [dgraph-io/dgraph#4554]
Hi, Dgraph,
    Recently, I am doing some experiments based on ldbc_snb benchmark. And I wan to test Dgraph on ldbc. And some users also want to do so. But I found graphQL+- has some limitations to implement the complex queries in ldbc_snb. So I want to know if you have implemented ldbc_snb benchmark for Dgraph? Could you please provide me a solution to run ldbc_snb benchmark on Dgraph?
    Thanks for your kindly support and I'm looking forward to your early reply!

**Comment by martinmr** [comment]
We have not implemented this benchmark and AFAIK we don't have any plans to do so.


What type of queries are you having trouble with?

—
Martin Martinez Rivera



https://dgraph.io

--- original message ---
On January 13, 2020, 6:24 AM PST notifications@github.com wrote:


Hi, Dgraph,

Recently, I am doing some experiments based on ldbc_snb benchmark. And I wan to test Dgraph on ldbc. And some users also want to do so. But I found graphQL+- has some limitations to implement the complex queries in ldbc_snb. So I want to know if you have implemented ldbc_snb benchmark for Dgraph? Could you please provide me a solution to run ldbc_snb benchmark on Dgraph?

Thanks for your kindly support and I'm looking forward to your early reply!

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by ouzensang** [comment]
@martinmr 
Thanks for your reply! There are many complex queries defined in ldbc_snb benchmark, such as finding some cycles, finding the shortest paths between two nodes and doing some computation among nodes in path, finding the next node by passing uncertain number of edges(showing in the following picture), and some more ....
![image](https://user-images.githubusercontent.com/30515579/72401323-a618a600-3786-11ea-9b8c-96ea3ff64d06.png)
Specific defination of the benchmark can be found in https://ldbc.github.io/ldbc_snb_docs/ldbc-snb-specification.pdf

**Comment by shekarm** [comment]
We don't have those kinds of algorithms natively in Dgraph with the sole exception of shortest paths.


You could still do it but you'd have to implement those algorithms as client code, which would probably be slower than a database that has this type of algorithms available natively.

--- original message ---
On January 13, 2020, 6:25 AM PST notifications@github.com wrote:


Hi, Dgraph,

Recently, I am doing some experiments based on ldbc_snb benchmark. And I wan to test Dgraph on ldbc. And some users also want to do so. But I found graphQL+- has some limitations to implement the complex queries in ldbc_snb. So I want to know if you have implemented ldbc_snb benchmark for Dgraph? Could you please provide me a solution to run ldbc_snb benchmark on Dgraph?

Thanks for your kindly support and I'm looking forward to your early reply!

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8815). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
