### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#457]
It would be nice to be have support for multiple databases/graphs. For example, we can have a graph for each tenant in a dgraph cluster, rather than needing to spin up a cluster for each tenant.

**Comment by manishrjain** [comment]
That's something we intend to work on soon.

**Comment by F21** [comment]
Good to see that this might happen soon! 😄 Is there any reason why this is tagged as commercial? Most databases support having multiple databases in the base/open-source version.

**Comment by manishrjain** [comment]
@F21 -- In Dgraph, there's no concept of multiple databases. In general, graphs can have clusters which don't touch each other; which is the equivalent of how databases work in SQL.

This issue is specifically to allow multiple clients running on the same cluster of Dgraph. Useful for providing Dgraph as a service by commercial entities; not useful for startups. Therefore, this goes under a commercial license.

**Comment by F21** [comment]
@manishrjain Makes sense!

How much isolation can I expect between the clusters? I am interested in using dgraph as a backing store for a few graph-oriented microservices, and it would be much simpler operationally to run 1 dgraph cluster rather than a cluster for each service. However, it would be nice to prevent 1 service from accidentally modifying or reading data from the cluster of another service.

**Comment by manishrjain** [comment]
It would be data level isolation for everyone. For shared servers, it won't be resource level isolation. But, we'd allow you to have dedicated machines for certain clients; specified via the groups config file.

**Comment by manishrjain** [comment]
This would be a commercial feature. So, closing this issue.
