### ISSUE TITLE
Export endpoint doesn't require authentication

### ISSUE THREAD

**Issue by animesh2049** [dgraph-io/dgraph#4758]
### What version of Dgraph are you using?
v2.0.0-beta1-26-g2ad482aff

### Have you tried reproducing the issue with the latest release?
Yes

### Steps to reproduce the issue (command/config used to run Dgraph).
Just send request to export endopoint, it will start export.

### Expected behaviour and actual result.
It should require authentication.

**Comment by MichelDiz** [comment]
We need to check if this is also true via GraphQL Admin operations.

**Comment by marvin-hansen** [comment]
@animesh2049  

This is a prevalent issue with the GraphQL endpoint although DGraph has some mechanism to [restrict admin & mutation operations](https://docs.dgraph.io/deploy/#whitelist-admin-operations) through IP whitelisting and you can do some [TLS stuff, if you really want](https://docs.dgraph.io/deploy/#tls-configuration).
 
Beyond that, you have a few options: 

1) Deploy an API manager such as Kong or Ambassador to add, proper SSL, authentication, routing and usage quotas.   
2) Use an API middleware such as Hasura 
3) Build your own API security mechanism  

Eventually, I ended up with a combination of 1 & 2 due to time constraints.
