### ISSUE TITLE
S3 backups not working

### ISSUE THREAD

**Issue by Aelbannan** [dgraph-io/dgraph#4964]
### What version of Dgraph are you using?
v2.0.0-beta
### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
16 GB RAM, Windows and Linux

### Steps to reproduce the issue (command/config used to run Dgraph).
Set AWS Access/Secret key as env variables. Key has correct permissions.

(Optional) Make bucket permissions completely public

Run `curl -XPOST localhost:8080/admin/backup -d "destination=s3://s3.us-west-2.amazonaws.com/<bucket name>?secure=false"`

### Expected behaviour and actual result.
Expected: Backup is sent to S3

Actual: `{"errors":[{"message":"Backup failed.","extensions":{"code":"while looking for bucket <bucket name> at host s3.us-west-2.amazonaws.com: Access Denied."}}]}`

**Comment by martinmr** [comment]
Have you set the env variable in every alpha? Every group leader has to contact aws.

Can you try to access the bucket with the same permissions via other means (e.g the aws cli) and see what happens. I am trying to rule out an issue with AWS permissions. I am not very familiar with them so I don't know if AmazonS3FullAccess is enough.

I remember Daniel had similar issues and the cause was that there's a hierarchy of permissions and one entry higher in the hierarchy was blocking access.

Also maybe print the credentials to the dgraph log to confirm they are what you expect.

**Comment by Aelbannan** [comment]
> Have you set the env variable in every alpha? Every group leader has to contact aws.

I only have one alpha right now, so this shouldn't be a problem.

> Can you try to access the bucket with the same permissions via other means (e.g the aws cli) and see what happens. I am trying to rule out an issue with AWS permissions. I am not very familiar with them so I don't know if AmazonS3FullAccess is enough.

Have done this and had no problem discovering buckets and uploading files to buckets.

> I remember Daniel had similar issues and the cause was that there's a hierarchy of permissions and one entry higher in the hierarchy was blocking access.

I'll explore this more in depth, this might be it.

> Also maybe print the credentials to the dgraph log to confirm they are what you expect.

Has been done, credentials are fine.

**Comment by Aelbannan** [comment]
Tried giving the key `AdministratorAccess` permission (global full access), still no luck. I think we can rule out permission problems.

**Comment by Aelbannan** [comment]
Was a docker bug

**Comment by jj0b** [comment]
@Aelbannan any more info on this? I'm running into the same error when using the export to S3 API from within the standalone Dgraph Docker container.
