### ISSUE TITLE
Residual predicates with RDF export endpoint

### ISSUE THREAD

**Issue by mehdiym** [dgraph-io/dgraph#5053]
### What version of Dgraph are you using?

1.2.2 and master 46dfaabe16d3d7aa6a1e1ba8af3f33451ad071db

### Steps to reproduce the issue (command/config used to run Dgraph).

* On ratel, drop some predicates
* Query the "/admin/export" endpoint

### Expected behaviour and actual result.

* Edit the g01.schema generated file
* The dropped predicates should be gone but they are not
* Their indexes has been removed though, they are now set as `default`

I checked the generated g01.rdf.gz, and there is no n-quad with those removed predicates.

**Comment by pawanrawal** [comment]
I have been able to reproduce the issue. After dropping a predicate, its schema type is changed to default and when it is exported we can see that the predicate is there in the schema file with `default` type. This is not a big problem because the user can insert new data for the predicate with a new schema type, but still it would be nice to not have the predicate be part of the exported schema after it is dropped.

**Comment by jarifibrahim** [comment]
Hey @mehdiym, this issue has been fixed in the master branch. Please do give it a try and let me know how it goes.
