### ISSUE TITLE
Fail to decompress and load export data

### ISSUE THREAD

**Issue by JimWen** [dgraph-io/dgraph#5204]
### What version of Dgraph are you using?

Dgraph version   : v1.2.2
Dgraph SHA-256   : 86e27921d3a53dbc4faba78e9c7d7879ce8bafd6006c9fd4b77220535b8ae1c2
Commit SHA-1     : 21cc8936
Commit timestamp : 2020-03-19 12:13:11 -0700
Branch           : HEAD
Go version       : go1.13.5

### Have you tried reproducing the issue with the latest release?

Only with latest 1.X version

### What is the hardware spec (RAM, OS)?

128G mem & 1.8T SSD

### Steps to reproduce the issue (command/config used to run Dgraph).

Export data with "curl localhost:8080/admin/export" and load data with bulkload

### Expected behaviour and actual result.

The export log is done and the log is as followings:

_I0414 20:50:53.194582   47261 log.go:34] Export Sent 1372402501 keys
I0414 20:50:53.197762   47261 export.go:581] Export DONE for group 1 at timestamp 111490001.
I0414 20:50:53.197784   47261 export.go:600] Export request: group_id:1 read_ts:111490001 unix_ts:1586860875 format:"rdf"  OK._

But it fail to decompress the export *.gz file, and the error info is as followings:

_invalid compressed data--format violated_

And it fail to bulkload, and the error info is as followings:

_2020/04/14 16:16:37 flate: corrupt input before offset 3005180

github.com/dgraph-io/dgraph/x.Check
        /tmp/go/src/github.com/dgraph-io/dgraph/x/error.go:42
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*loader).mapStage.func2
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/loader.go:207
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357_

Why does this happen, when i test with little data, that export and bulkload funtion works fine, but it's unsuitable for big data here. The total gzip file size is 10G. 

Wait for your help, thank you!!!

**Comment by JimWen** [comment]
Anybody can help me ?

**Comment by shekarm** [comment]
@JimWen I will find someone in the team.

**Comment by MichelDiz** [comment]
That seems a very curious case. @JimWen would you mind to share or simulate with samples this case? so I can reproduce at my side and find an engineer to fix or help you?

The questions:

1. Is this happening on the master branch or just the reported version?
2. This happens just with big sizes? have you exported a small dataset and then exported again a big one? (I think this is a bug I have found, but I still not sure)
3. The error you got comes from Dgraph import or the OS?
4. I see that you have an error about "offset" this might happen due to the wrong usage of the Zero instance (or group). If you export a dataset and wanna reimport you have to use a new cluster (you have to delete all files from Alphas and Zero).

A detailed step bu step would help a lot.

Cheers.

**Comment by ashish-goswami** [comment]
Hey @JimWen, adding to @MichelDiz's questions: is it happening every time you perform an export?

**Comment by JimWen** [comment]
@MichelDiz @ashish-goswami  I'm so sorry, apologies for the late reply, but it has been ok in v1.2.3. So i close it.
