### ISSUE TITLE
Ratel does not display manually set Type in the schema tab at Types or Predicates.

### ISSUE THREAD

**Issue by mrnijboer** [dgraph-io/dgraph#5254]
### What version of Dgraph are you using?
20.03

### Have you tried reproducing the issue with the latest release?
Issue is with latest release.

### What is the hardware spec (RAM, OS)?
macOS 8GB

### Steps to reproduce the issue (command/config used to run Dgraph).
1. Create node with "dgraph.type" in JSON:
`{
"dgraph.type": "Post",
"title": "string",
...
}`

2. See Ratel schema on `localhost:8000`. Type `Post` is not visible, nor predicate `dgraph.type`.

3. Query the node with `func: type(Post)` or as filter `@filter (type(Post))`. The query happens correctly with Type set.

### Expected behaviour and actual result.
Types set via "dgraph.type", as per the documentation [https://dgraph.io/docs/query-language/#setting-the-type-of-a-node](https://dgraph.io/docs/query-language/#setting-the-type-of-a-node), should appear in Ratel dashboard as either Type or Predicate.

Types set via JSON do not, however, show up in the Ratel dashboard. Functionally they work as expected and I have not found a problem apart form the dashboard.

**Comment by MichelDiz** [comment]
Have you created the type schema?
```
type Post {
  title
   ...
}
```

**Comment by paulftw** [comment]
Github is unstable right now, seems like this issue is being transferred to Ratel.
If so -- I disagree.

Here's the response I posted to the Ratel issue:

> Tried running a mutation ` { "set": { "dgraph.type": "Post", "title": "string" } } `
> followed by a schema query -- `schema {}`
> Dgraph chema response doesn't contain the type created that way.
> I don't think this qualifies as a bug in Ratel -- Ratel shows the data that server is returning. Why server isn't returning the type is another question.

**Comment by paulftw** [comment]
@mrnijboer Speaking of Dgraph response -- you need to create type explicitly before using it in mutations. Similar to how you'd create a table in SQL before inserting into it.

That's Dgraph's current behavior. I'll let @MichelDiz and rest of the backend team decide whether they want to change that behavior.

**Comment by mrnijboer** [comment]
OK, clear. Thanks.

**Comment by MichelDiz** [comment]
@mrnijboer One thing that was not evident is exactly what you are looking for. Are you looking for the predicate "dgraph.type" in the Schema panel, or for the Type in Schema/Types panel?

If the answer is the first option, it is not possible. "dgraph.type" is a reserved predicate. It is not visible to users.

If the answer is the second option, you need to define the Type definition. Go to, Schema/Types panel. Click in Add Type. Give it the same name as "dgraph.type" you have and add the predicates for that type. That's the only way to "assemble" Type definition.

Type definition can't be done via mutation (JSON or RDF). They are made via Alter.

If that is not the point let me know. Otherwise please close this issue.

Thanks.

**Comment by mrnijboer** [comment]
> If the answer is the first option, it is not possible. "dgraph.type" is a reserved predicate. It is not visible to users.

Understood. I was looking to create a Type with "dgraph.type". The proper way is to create a Type upfront via alter. Thanks.
