### ISSUE TITLE
Support ignore directive

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#526]
For a query like this:

```
{
	var(allof(type.object.name.en, "cox")) {
		film.actor.film {
			CF as film.performance.film {
				CC as film.film.country
			}
		}
	}
	var(allof(type.object.name.en, "aniston")) {
		film.actor.film {
			JF as film.performance.film {
				JC as film.film.country
			}
		}
	}

	country(CC) @filter(id(JC)) {
		c: type.object.name.en
		~film.film.country @filter(id(CF) || id(JF)) {
			f: type.object.name.en
			film.film.starring {
				film.performance.actor @filter(anyof(type.object.name.en, "cox aniston")) {
					a: type.object.name.en
				}
			}
		}
	}
}
```

We get a lot of nesting in the results, which is annoying to parse, particularly if you are only interested in certain levels.

I propose adding an `@ignore` directive, which would attach the children of that level to its parents. 

`A --> B @ignore --> C`  converts to `A --> C`. I think this can be done after generating the result outputnode tree, and before they're marshalled.

**Comment by manishrjain** [comment]
This might not be required due to normalize. So, do this after normalize.

**Comment by pawanrawal** [comment]
We are not entirely sure of the use case for this, hence have decided not to implement this for now. We can prioritise it if someone thinks this is useful to them.

**Comment by calummoore** [comment]
Hi both - @manishrjain @pawanrawal 

It would be really helpful to have a way to ignore aggregation queries in a returned query block. Most of the time when you're requesting an aggregation, it's because there are too many nodes to return and you only need the aggregated value.

For example, I want to be able to run the following query, without returning any of the individual `usage.count` predicates (for which there could be a very large number!).

```
query {
  root (func: eq(node.type, "customer")) {
    id: uid
    customer.name
    sum(val(A)) 
    ~usage.customer {
      A as usage.count
    }
  }
}
```

@pawanrawal showed me a way to get around this using a var block, which I can use for now, but it adds a lot more complexity to my queries for what I'm sure is a popular use case.

It would be really helpful to have a kind of `@ignore` directive, so I can tell Dgraph not to return anything (i.e. I just want to get the data for the variables).

**Comment by manishrjain** [comment]
Haven't heard the community ask for this.
