### ISSUE TITLE
(GraphQL API) Bidirectional edge not generated for interface field

### ISSUE THREAD

**Issue by CosmicPangolin** [dgraph-io/dgraph#5393]
What version of Dgraph are you using?
20.03.1

Have you tried reproducing the issue with the latest release?
Yep

What is the hardware spec (RAM, OS)?
N/A

Steps to reproduce the issue (command/config used to run Dgraph).
Consider the following schema:

```
interface File {
     users: [User!] @hasInverse(field: files)
}

type Image implements File {
}

type User {
     files: [File!]
}

```

Expected behaviour and actual result.
When I save an Image with a User, I would expect to be able to traverse from User back to that Image via User.files.  Currently only the Image ---> User edge is created

**Comment by vadavallipavan** [comment]
i am having the same issue
Below is the graphQL schema:
type Book {
    id: ID!
    name : String!  @search(by: [term])
    tags : [Tag!]! @hasInverse(field:books)
    description : String
}type Tag {
    id: ID!
    text: String!  @search(by: [hash])
    books:[Book!]!
}
Below is the mutation
{
 set {
    _:awsbook <Book.name> "awesomebook1" .
     _:awsbook <dgraph.type> "Book" .
  	_:awsbook <Book.tags> _:awstag .
  	_:awstag <Tag.text> "AWESOME" .
  	_:awstag <dgraph.type> "Tag" .
  }
}
Below is the reverse query : 0x2 --> uid of generated tag
{
  booksFound (func: uid(0x2)) {
		uid
    Tag.text
    dgraph.type
 	Tag.books {
     		uid
			  Book.name
			}
}
}

Tag.books node is always empty
However the forward query works
{
  nooksFound (func: uid(0x3)) {
		uid
    Book.name
    dgraph.type
 	Book.tags {
     		uid
    Tag.text
			 
			}
}
}

Can you please advise

**Comment by vadavallipavan** [comment]
Update:
After discussing with Pawan in slack, the conclusion is graphQL mutations will take care of generating the reverse edges when needed , we cant really mix graphql+- queries/mutations with graphql schema.

**Comment by pawanrawal** [comment]
@vadavallipavan was facing a different issue which is not a bug. We still need to investigate the issue that @CosmicPangolin is facing. @JatinDevDG is currently investigating it.

**Comment by JatinDevDG** [comment]
Given schema was not working, so i fixed it and added details to it  

interface File {
id: ID!
name:String !
users: [User!] @hasInverse(field: files)

}
type Image implements File {
description:String
}
type User {
name:String !
files: [File!]
}


we can access users from images directly.But the reason you were not able to access  images from user is that index is created in File interface and it can't access image fields.

 

But even then we can access  file fields from users and even image fields which are in files by first creating images and  use there id’s whille creating users.

![image](https://user-images.githubusercontent.com/64803093/83118758-68d90300-a0ec-11ea-9c96-3a4c7f3af99f.png)

In above mutation, id is the id of image already created. In result we can see the  detail of that image, but we can’t see description from here because that is in image type.


But if you really want to access image fields ,we have to add index in image type like belows and refer to image in users.

interface File {
id: ID!
name:String !

}
type Image implements File {
users: [User!] @hasInverse(field: files)
description:String !
}
type User {
name:String !
files: [Image!]
}

Below mutation adds image and user.

![image](https://user-images.githubusercontent.com/64803093/83118808-7abaa600-a0ec-11ea-89ae-91c0420d2cd0.png)

Below mutation create a user and add a new image into it.Now, you can also access description in the result.


![image](https://user-images.githubusercontent.com/64803093/83118844-87d79500-a0ec-11ea-84b2-82692c8dabb6.png)

**Comment by CosmicPangolin** [comment]
@JatinDevDG 

Thanks for checking this out - just now taking a look.  

Is the thought that your second solution is sufficent (pushing the users predicate into the concrete types and using a concrete type instead of interface in the schema)?  Those actions seems to defeat the purpose of having an interface to begin with: we lose the ability to consolidate shared predicates into the interface and the ability to use multiple concrete types with a given predicate.

I would expect to be able to run a query on User.files with '...on Image {}' syntax from the first schema.

**Comment by MichaelJCompton** [comment]
Hi, I've been trying this out and it works as I expected.  

Here's what I did.

schema:

```graphql
interface File {
    filename: String
    users: [User!] @hasInverse(field: files)
}

type Image implements File {
    format: String # gif, etc
}

type User {
    id: ID!
    name: String
    files: [File!]
}
```

Once that was added, I ran this mutation:

```graphql
mutation {
  addUser(input: [ {name: "michael"} ]) {
    user {
      id
      name
    }
  }
}
```

it gives me back

```graphql
  "data": {
    "addUser": {
      "user": [
        {
          "id": "0x2",
          "name": "michael"
        }
      ]
    }
  }
```

Then I add an image and link it to this user

```graphql
mutation {
 addImage(input: [ { 
  filename: "my file", 
  format: "png", 
  users: [ { id: "0x2" } ]} ]) {
    image {
      filename
      format
      users {
        name
      }
    }
  }
}
```

which returns

```
  "data": {
    "addImage": {
      "image": [
        {
          "filename": "my file",
          "format": "png",
          "users": [
            {
              "name": "michael"
            }
          ]
        }
      ]
    }
  }
```

Then I can query through the user, and use a fragment on the type (`format` only applies to images, not all files)

```graphql
query {
  queryUser {
    id
    name
    files {
      filename
      ... on Image {
        format
      }
    }
  }
}
```

that gives me what I expect

```graphql
  "data": {
    "queryUser": [
      {
        "id": "0x2",
        "name": "michael",
        "files": [
          {
            "filename": "my file",
            "format": "png"
          }
        ]
      }
    ]
  }
```

@CosmicPangolin, get back to me and let me know if it is something else that you are trying to do.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8525). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
