### ISSUE TITLE
Lack of documentation on using the Go client

### ISSUE THREAD

**Issue by etix** [dgraph-io/dgraph#548]
The [Go example](https://wiki.dgraph.io/Clients#Go) given on the [clients documentation](https://wiki.dgraph.io/Clients) is interesting in the way it shows how to manipulate different properties on objects but doesn't really explain how to use dgraph in Go (and in other languages) to create a real-world graph.

In the [Gru](https://github.com/dgraph-io/gru) project you seem to be using an RDF-like terminology to create the structure of the graph. Is it the recommended / only way to do so?

It would be nice to have an end-to-end example on how to create a basic graph from insertion of vertices and edges to the final query.

**Comment by RXminuS** [comment]
This I'd like to see in the example:
- Creating nodes & edges with both id's and _xid_'s
- Creating facets
- Removing nodes
- Root filters and filters
- Filtering by facets

Ideally one example would create the graphs visible on your homepage so that you have a nice visual picture with it as well.

**Comment by pawanrawal** [comment]
Hi @RXminuS 

Soon we will have the Go client and cURL examples side by side in our docs. That will make things easier. I can answer your question for now.

1. Any query (and also mutation) that you can perform with cURL also works with the Go client, so you can do all the filtering queries you mentioned above by putting it inside `req.SetQuery(query)` as mentioned in the Wiki.

2. We don't allow removing nodes, we just allow removing connection between nodes. I have updated the Wiki to include an example for that.

3. Creating nodes and edges with xids/uids should work, you just supply them in the Subject and ObjectId field. Let me know if that doesn't work you.

4. You can use the raw mutations from the Query Language spec for creating facets for now. I will add support so that it can be part of `graphp.NQuad`.

Let me know if something is not clear.

We will also be coming up with some use cases (recommendation engines/ fraud detection) with the code on how to build them using Dgraph. That will help I guess. In the meantime, feel free to update the Wiki to add any examples that you think would be useful.

**Comment by MichaelJCompton** [comment]
There are GoDocs with examples here

https://godoc.org/github.com/dgraph-io/dgraph/client

larger examples here

https://github.com/dgraph-io/dgraph/tree/master/wiki/resources/examples/goclient

and a blog post about the client

https://open.dgraph.io/post/client0.8.0/
