### ISSUE TITLE
Graphql failed to update nest values

### ISSUE THREAD

**Issue by conanchen** [dgraph-io/dgraph#5550]
### What version of Dgraph are you using? 
20.03.1
### Have you tried reproducing the issue with the latest release?
NO

### What is the hardware spec (RAM, OS)?
Centos7

### Steps to reproduce the issue (command/config used to run Dgraph).
We have Schema as 
type Store implements Node{
id:ID
identifier: String
name: String
place: Place
}
type Place implements Node{
id: ID
identifier: String
name: String
}

1. we have "Store" id as "0x2725" and the store has "Place" with id "0x2726" 
query{
   getStore(id: "0x2725"){
     id
     identifier
     name
     dateModified
     place{
       id
       identifier
       name
     }
   }
 }
2. I can mutate the place name sucessfully using the updatePlace api
 mutation{
   updatePlace(input:{filter:{id:["0x2726"]},set:{name:"place name"}}){
     numUids
   }
 }

3. but failed to update the store's place using updateStore api, 

mutation {
  updateStore(
    input: {
      filter: { id: ["0x2725"] }
      set: {
        place: {
          id: "0x2726"
          name: "update name3"
        }
      }
    }
  ) {
    numUids
    store {
      id
      identifier
      dateModified
      place {
        id
        name
      }
    }
  }
}

### Expected behaviour and actual result.
update nest value sucessfully
![1590813226978](https://user-images.githubusercontent.com/1233799/83319521-de221080-a271-11ea-8836-7979af7244a9.jpg)

**Comment by abhimanyusinghgaur** [comment]
Hey @conanchen,

It is the expected behaviour.
This is how the GraphQL api has been designed. You can only update the fields of a type in the update mutation for that type, not the fields of a nested type. 

If you want to update the fields of an existing `Place` then you will have to use the `updatePlace` api, you can't do it through `updateStore`.

What you can do for `Place` through update store is, two things:
* you can link an existing place to the store using only the id of the place, OR
* you can specify any other fields except place id for place in `updateStore`, and it will create a new place with those details and link it to the store.

What you have shown in the picture, uses both id and other fields, in which case, since id is given, it takes preference and the existing place with that id is linked to store.

I hope this clarifies the issue. Feel free to re-open if you have any more doubts .
