### ISSUE TITLE
add graphiql-explorer

### ISSUE THREAD

**Issue by ctwhome** [dgraph-io/dgraph#5651]
## Experience Report
Add Graphiql Plugin explorer to engage with the users more. 

### Any external references to support your case
https://github.com/OneGraph/graphiql-explorer

**Comment by MichaelJCompton** [comment]
Hi, thanks for the request.  Are you asking for the Dgraph server to respond with a GraphiQL instance if you visit localhost:8080/graphql in a browser, for example?

If so, we could do that.  Maybe we'd also have a command line flag so that you can turn that feature on/off on hour server.

There are a bunch of options ... you wan the OneGraph version?  It's got the query builder.

**Comment by ctwhome** [comment]
both options that you mention are good! localhost:8080/graphql, and maybe inside the dgraph console..?
the most important option, in my opinion, is indeed the query builder 🤩

**Comment by MichaelJCompton** [comment]
Great.  I'll mark this as accepted so it gets into our backlog.  No idea just now, when it will get picked up - I'll drop a note here if that becomes clear.

**Comment by ctwhome** [comment]
Super, thanks!

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8854). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
