### ISSUE TITLE
Export/Import option in dgo

### ISSUE THREAD

**Issue by praneelrathore** [dgraph-io/dgraph#5720]
## Experience Report

Reopening this here - https://github.com/dgraph-io/dgo/issues/125

Currently for exporting data, as per the docs [here](https://dgraph.io/docs/deploy/#exporting-database), it is required to run the mentioned GraphQL mutation at the /admin endpoint. This requires either logging in the instance of alpha, or whitelisting some server that can connect to the alpha. This process doesn't seem right when it comes to running Dgraph deployment on production.

It would be really helpful to have export/import client API's, that will take an alpha's address, and run the mentioned mutation on the doc.

**Comment by MichelDiz** [comment]
As this is an admin task. It doesn't make sense a client has this. It should be on Ratel UI tho. As we have "Drop data". Do you have any example of other DBs doing this in the client end?

Also, you can potentially add a GraphQL client and do any Admin task there.

**Comment by praneelrathore** [comment]
> As this is an admin task. It doesn't make sense a client has this.

Agreed. What I wanted was that it would be a lot easier to have some implementation in the client for this, just like we have for altering the schema etc. It can just take the path to export the data to as an input, for example. We can then  implement limited access for running such operations.

> Also, you can potentially add a GraphQL go client and do any Admin task there.

Alright, can you point me to some example where I can evaluate this approach.

Also, I forgot to mention another issue that I opened for this as well https://github.com/dgraph-io/dgo/issues/124

**Comment by MichelDiz** [comment]
You can find some info about admin GraphQL procedures here https://graphql.dgraph.io/admin

Also, you can use any kind of client. The GraphQL ecosystem has several solutions for that. Your client end can have dgo and a GraphQL client at the same time.

IMHO, add these operations to clients would be hard to maintain. Today we maintain GraphQL and HTTP endpoints (it seems, the HTTP one, will be discontinued in favor of GraphQL - I hope not). Adding these admin procedures to Dgo would increase a bit the complexity and also force us to add it to all clients. Which, again, increase maintenance complexity.

Ping @parasssh - FYI, the issue was added to backlog in Dgo repo. But not sure if it will be implemented due to the facts above.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
