### ISSUE TITLE
Testing issue auto-closer

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#5947]
**GitHub Issues are deprecated. Use [Discuss Issues](https://discuss.dgraph.io/c/issues/dgraph/38) for reporting issues about this repository.**

**Comment by martaver** [comment]
This is singularly a terrible idea.

The new discussion tool looks to be an own-rolled app and I, personally, can't even log in with my GitHub credentials.

The new discussion format lacks many, many features that allow for meaningful conversations in GitHub issues. GitHub allows for discussions that link PRs, issues, ping relevant users etc. and allow individuals to participate in multiple repositories at once.

Your users don't need yet another discussion tool.

This move actively discourages users from participating in the improvement of your product by introducing orders of magnitude more friction and withholding vital features. In this way it provides the appearance that the dgraph team doesn't want to deal with real world user issues, and it also inhibits good software citizenship.

Please reconsider this move. It is deeply affecting the perceived professionalism of the dgraph team.

**Comment by martaver** [comment]
FWIW, `snowpack` recently went through the same experience. https://github.com/pikapkg/snowpack/issues/606

GitHub is actually releasing a new feature called `Discussions` to cater for exactly this scenario, and `snowpack` was able to get early access to it.

I'm not sure if this is appropriate, but might @gr2m be able to help the `dgraph` team in the Discussions early access? Apologies if this is out of line.

**Comment by gr2m** [comment]
@manishrjain is this something you’d be interested in trying? Do you have any questions or concerns?

**Comment by WolfgangFahl** [comment]
https://dgraph.io/docs/tutorials/ still points to github and it would be good if the issues could be found here.

**Comment by corysimmons** [comment]
Thoughts on deprecating Discuss in favor of Github Discussions so devs can get all their notifications in one place and don't have to make yet another account? Also the UI is infinitely better.

**Comment by homerjam** [comment]
This is so confusing. Almost every issue on Discuss links to Github in some way and vice versa. Seems like a lot of unnecessary friction to me.

**Comment by mysticaltech** [comment]
First time I have ever seen an open-source project on Github without issues! That can mean only one thing, this is not a true Github-style open-source project (yes Apache 2.0 yada yada). Issues shine a bad light on the project, and you do not want to provide support for free. So in truth, this open-source project is probably just a bait for your paid option. Really sad!

**Comment by andrewbanchich** [comment]
@manishrjain What is the reason for this? It is definitely a bizarre move and I think it's clear the community dislikes it a great deal. Maybe some insight into why this decisions was made could help clear things up.

**Comment by mysticaltech** [comment]
Yes, the issue must stay! Github is not Github without them. This is completely bizarre and indicates that something is being hidden.

**Comment by benwoodward** [comment]
Initially when I saw this post I just thought people were being contrarian or something, but after trying to get to grips with Dgraph and feeling like Discourse was a major piece of friction in the process, I'm adding another vote to ditch Discourse. 

Recently I submitted some ideas on a Github Discussions board, and by comparison it is a joy to use. It is simple to understand, it works well in the official Github mobile app and it triggers Github notifications. Plus, it makes sense to talk about the code in this repo _in this repo_, does it not?

My specific frustrations with Discourse:

## The UI is frustrating

I mean, look at this new post UI, drives me nuts every time:

![image](https://user-images.githubusercontent.com/1472981/113050864-d3be0380-9201-11eb-97c6-2ca4ede4cfdb.png)

- Posts are called a 'Topics', which took me a while to realise aren't categories, but posts.
- To create a new post/topic I have to press a button called "create a Draft" at the top, and then the *new topic* dialog appers at the bottom
- The dialog that appears has button ➕  that appears to be labeled 'Create a new topic' but if you press it it reveals a new button that says "Create a new message". Huh?

![image](https://user-images.githubusercontent.com/1472981/113051179-2e575f80-9202-11eb-9eff-cee35fde4573.png)

- Every time I add a title, this yellow warning thing pops up: 

![image](https://user-images.githubusercontent.com/1472981/113051333-56df5980-9202-11eb-809a-8fbf9bc701bb.png)

- It says to hit `esc` to dismiss, but hitting `esc` key doesn't do anything. 

![image](https://user-images.githubusercontent.com/1472981/113051437-72e2fb00-9202-11eb-8637-e4eb0e82da62.png)

- Then every time you have to locate your mouse cursor over this little bar to drag it up so you can actually see what you're typing: 

![image](https://user-images.githubusercontent.com/1472981/113051584-a160d600-9202-11eb-90fd-c0d67e611e7f.png)

- There are so many Discourse categories and tags, and the UI is so odd that I often just don't bother posting. I came to Github to post a bug with a link to a specific line of code, saw that I had to go back to Discourse and I didn't bother because Discourse just doesn't seem like the right place to discuss code that is in this repo, ***this repo seems like the right place to discuss code that is in this repo***.

## Notifications

Github also has a bunch of third party tools that work with it, for example I use https://www.gitify.io which allows me to create an issue and forget about it because I'll see a green notification in my menu bar when someone replies.

![image](https://user-images.githubusercontent.com/1472981/113055821-86449500-9207-11eb-9295-ba38b6f74b70.png)

With Discourse I have to remember to keep going back to the board and refreshing the page to see if I've got any notifications and more often than not the notifications are from Discourse about some kind of Discourse achievement badge I've been awarded for figuring out how to edit my post or something. 

![image](https://user-images.githubusercontent.com/1472981/113056347-2a2e4080-9208-11eb-8200-3e1500f793b6.png)

**Comment by jonorozcoc** [comment]
Any news on this?

**Comment by cbrake** [comment]
I think there is a place for both github issues (bugs, and code focused discussions). Discourse is a better platform for community discussions, support, etc. Github discussions are a neat idea, but it is likely they are not at the functional level of Discourse yet. The weekly digest option in discourse is an amazing feature and allows people to keep up with a community, but not be overwhelmed by noise.

**Comment by andrewbanchich** [comment]
@cbrake I don't mind so much if they want to use Discourse or something else for discussions. I do mind about the GitHub Issues.

Not sure what they're thinking making us use Discourse for issues.

**Comment by chengxuncc** [comment]
I don't think community is running well.
https://github.com/syncthing/syncthing/commit/7892547873c805ef4066f68ea1097d083a759725
https://github.com/jaegertracing/jaeger/issues/2459#issuecomment-691093162

**Comment by ahfarmer** [comment]
Now that github issues are back open, is it time to 'unpin' this issue? 😄

**Comment by danielmai** [comment]
@ahfarmer Good point. This is now unpinned.

**Comment by WolfgangFahl** [comment]
No reason to close this as long as issues are not discussed here. The overview
![grafik](https://user-images.githubusercontent.com/1336221/149497934-03ee1a23-eecc-47b2-a92c-b615ba245efc.png)
is IMHO misleading

Please reopen this issue and fix it by using github issues again.

**Comment by ahfarmer** [comment]
@WolfgangFahl GitHub issues were re-opened very recently. It will take time for users to migrate back from the discuss forum to github issues. There's nothing else that can be done for this issue.
