### ISSUE TITLE
 Modifying node and edge creation behavior based on xid

### ISSUE THREAD

**Issue by vishaljangid1729** [dgraph-io/dgraph#8661]
### Question.

Hello Team,

I am interested in modifying the node and edge creation behaviour in Dgraph. Dgraph creates a new node and points to it if no `uid` is specified. However, I would like to achieve this behaviour based on the `xid `value as well.

I have studied the codebase and the relevant documentation, but I still have trouble locating the code that handles node and edge creation. I would greatly appreciate it if someone could guide how I can modify the node and edge creation behaviour based on the `xid` value.

In particular, I would like to know the following:

- Which packages and files in the codebase are responsible for creating new nodes and edges?

- How does Dgraph handle the creation of new nodes and edges, and how is this reflected in the code?

- How can I modify the behaviour of node and edge creation to take the `xid` value into consideration?

- Do you know if there are any potential issues or considerations that I need to be aware of when I modify this behaviour?

Thank you for your help!

Best regards,
Vishal Jangid

**Comment by MichelDiz** [comment]
To use XID you can follow:

- External IDs and Upsert Block -> https://dgraph.io/docs/mutations/external-ids-upsert-block/
- Using with liveload -> https://discuss.dgraph.io/t/what-is-xid-in-live-loader-upsert-mode/15103/2

>Do you know if there are any potential issues or considerations that I need to be aware of when I modify this behaviour?

Your objective is very difficult to do. I think it's not feasible, because Dgraph is UID based. Any support for XIDs or any other means of third-party identification adds complexity and latency. The way Dgraph is designed today is for maximum performance using UIDs that act as addresses(like RAM addresses). So it's fast and doesn't need indexing. In the other hand  XID and any other ID will need indexing and will not have the same benefits as using UID.

**Comment by mangalaman93** [comment]
@vishaljangid1729 Would you mind explaining what use case you have where you would prefer to use XID instead of UID? The way Dgraph works is that, we use UIDs so that we can ensure their uniqueness as well as it simplifies query processing significantly. Usually, what we have seen is that storing the mapping from UIDs to XIDs serve most use cases.

If you would just like to get into the code, you should follow the code in edgraph/server.go and look for doMutate function.
