### ISSUE TITLE
[FEATURE]: Ability to query DQL schema based data using GraphQL

### ISSUE THREAD

**Issue by saivarunk** [dgraph-io/dgraph#8830]
### Use case

It would be great if we can extend the support of GraphQL queries on top of the data created using DQL schema. It helps in using GraphQL features like introspection.

**Comment by MichelDiz** [comment]
Sorry, I can not follow. Do you mean something like this https://dgraph.io/docs/graphql-dql/?

**Comment by saivarunk** [comment]
Yes @MichelDiz, if we could still use the /graphql endpoint for schema created by DQL, that would be very helpful.

**Comment by MichelDiz** [comment]
I understand your perspective. However, this is highly complex in relation to Dgraph at present. It would require the same level of personnel and resource investment that we've spent years pouring into GraphQL, just to replicate the same behavior in DQL. I believe this would be a fruitless investment, given that you could simply use GraphQL instead.

Indeed, DQL needs improvement, among other things. However, introspection is a step further. It is possible, but it comes at a high cost. The interoperability, which we will increasingly gain over time, will assist. But it won't be a magic fix. DQL operates on a dynamic and flexible model, unlike GraphQL which is rigid and predictable. These two factors make maintenance and the addition of introspection features straightforward in GraphQL.

In my opinion, to establish an introspection model, for instance, we would need to adopt rigidity. Standardize everything. And by doing so, we may become rigid and unyielding. It would result in a highly opinionated database. And that might not be appreciated by many.

Cheers.

**Comment by saivarunk** [comment]
@MichelDiz really appreciate you taking the time to answer my request. I agree with your assessment of GraphQL (predictability) & DQL (flexibility) and why it's easy to introspection with GraphQL.

**Comment by MichelDiz** [comment]
In the near future we will have a new Type System, a more Graphy one. We're working on it. There will be more interoperability between GraphQL and DQL. But some things like introspection won't be exactly equal or 1:1 all the time. Because GraphQL uses a factory pattern to create CRUD queries. These characteristics cannot be supported in the medium term or maybe ever cuz the CRUD is based on GraphQL schema and it is a dynamic creation. DQL will always be flexible tho.

Let me close this.

Let me know if you have more questions.

Cheers.
