### ISSUE TITLE
UI: Facets not displayed on edges.

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#972]
```
mutation {
  set{
    <a> <pa> <b> (w1=1, w2=2, w3=3) .
    <b> <pa> <c> (w1=2, w3=2) . 
    <c> <pa> <d> (w3=1, w1=1) .
  }
}

{
    shortest(from: a, to: d) {
      pa @facets(w3)
    }
}
```

The facets are not showing up on the edges in the UI.

**Comment by sungwoncho** [comment]
Fixed in https://github.com/dgraph-io/dgraph/pull/974.

The issue: facets on UID edges were not being displayed, while facets on edges to scalar values were being displayed.

The reason: facets on UID edges are displayed on edges in Dgraph browser. Facets on scalar edges are displayed on nodes. Dgraph browser assumed that only nodes have facets.
